---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 17-10-2025

---
<h2>CDT Weekly Newsletter</h2><br><ul><li>Message from the Director</li><li>AI Lunch and Learn Seminars</li><li>Conception X 2026 – applications are now open</li><li>Digital Health Seminar Series</li><li>Turing Seminar Series</li><li>Bristol Doctoral College (BDC) Events and Opportunities</li><li>Reference management: EndNote Online – organiser: Library - Subject Support</li><li>Around Bristol</li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b>Message from the Director</b><br><div id="WACViewPanel_ClipboardElement" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0" contenteditable="false" spellcheck="false">
<div class="OutlineElement Ltr SCXW212060435 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW212060435 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW212060435 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW212060435 BCX2">I am sure many of you have seen bad examples of using generative AI in research, paper reviewing, paper writing etc. I am equally sure that many of you have found ways to use </span><span class="NormalTextRun SpellingErrorV2Themed SCXW212060435 BCX2">GenAI</span><span class="NormalTextRun SCXW212060435 BCX2"> in productive ways while </span><span class="NormalTextRun SCXW212060435 BCX2">steering clear of</span><span class="NormalTextRun SCXW212060435 BCX2"> the edges of scientific propriety. If this </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW212060435 BCX2">is</span> <span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW212060435 BCX2">you</span><span class="NormalTextRun SCXW212060435 BCX2"> then I want to hear from you. I am planning to </span><span class="NormalTextRun SpellingErrorV2Themed SCXW212060435 BCX2">organise</span><span class="NormalTextRun SCXW212060435 BCX2"> an end-of-year CDT workshop on the use of </span><span class="NormalTextRun SpellingErrorV2Themed SCXW212060435 BCX2">GenAI</span><span class="NormalTextRun SCXW212060435 BCX2"> in academic research: the good, the </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW212060435 BCX2">bad</span><span class="NormalTextRun SCXW212060435 BCX2"> and the ugly. Please get in touch if you have </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW212060435 BCX2">ideas</span><span class="NormalTextRun SCXW212060435 BCX2"> about </span><span class="NormalTextRun SCXW212060435 BCX2">possible discussion</span><span class="NormalTextRun SCXW212060435 BCX2"> topics and sessions.</span></span><span class="EOP SCXW212060435 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:0,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
</div><br><br><b>AI Lunch and Learn Seminars</b><br><div id="WACViewPanel_ClipboardElement" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0" contenteditable="false" spellcheck="false">
<div class="SCXW8584375 BCX2">
<div class="ListContainerWrapper SCXW8584375 BCX2">
<ol class="NumberListStyle1 SCXW8584375 BCX2" role="list" start="1">
<li class="OutlineElement Ltr SCXW8584375 BCX2" style="display: block; margin-left: 24px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="41" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">Wei-Hong Li</span><span class="NormalTextRun SCXW8584375 BCX2">: </span><span class="NormalTextRun SCXW8584375 BCX2">Universal AI: Toward Balanced, Efficient, and 3D-Aware Learning</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">Date</span></span><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">: 22 October, pizza from 13:30 &ndash; 14:00 followed by the talk from 14:00 &ndash; 15:00</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">Location</span></span><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">: R</span><span class="NormalTextRun SCXW8584375 BCX2">oom</span><span class="NormalTextRun SCXW8584375 BCX2"> 1.07, Queen's Building</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">Abstract</span></span><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">: Modern AI systems achieve remarkable performance on specialized tasks, yet they often struggle to generalize across domains, modalities, and supervision levels. Bridging these divides between tasks, data sources, and 2D/3D understanding is essential for building universal and fair intelligence that can adapt flexibly to real-world scenarios. Such capabilities would unlock broad applications spanning autonomous </span><span class="NormalTextRun SCXW8584375 BCX2">perception</span><span class="NormalTextRun SCXW8584375 BCX2">, multimodal generation, embodied AI, and scientific discovery.&nbsp;</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">In this talk, I will present our recent efforts toward Universal AI, a research direction that aims to learn balanced, data-efficient, and geometrically grounded representations. I will first introduce methods for </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW8584375 BCX2">learn</span><span class="NormalTextRun SCXW8584375 BCX2"> balanced and transferable representations through a single network that </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW8584375 BCX2">generalize</span><span class="NormalTextRun SCXW8584375 BCX2"> to diverse tasks, domains, and in cross-domain few-shot scenarios and diffusion models. I will then discuss approaches for learning from partially annotated data, enabling effective supervision sharing across dense prediction tasks. Finally, I will highlight our latest work on 3D-aware understanding and compositional generation, where geometric priors and language guidance empower models to reason </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW8584375 BCX2">about</span><span class="NormalTextRun SCXW8584375 BCX2"> space, structure, and semantics in a unified framework.&nbsp;</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
</div>
<div class="SCXW8584375 BCX2">
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">Bio</span></span><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: normal; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">: Wei-Hong Li is an Assistant Professor </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW8584375 BCX2">in</span><span class="NormalTextRun SCXW8584375 BCX2"> the School of Computer Science at the University of Bristol, and a faculty member of the </span><span class="NormalTextRun SpellingErrorV2Themed SCXW8584375 BCX2">MaVi</span><span class="NormalTextRun SCXW8584375 BCX2"> group. He is also a member of ELLIS. He received his PhD from the University of Edinburgh, advised by Hakan Bilen and Timothy Hospedales, and </span><span class="NormalTextRun SCXW8584375 BCX2">subsequently</span><span class="NormalTextRun SCXW8584375 BCX2"> worked as a postdoctoral researcher there. He was also a postdoctoral fellow at the </span><span class="NormalTextRun SpellingErrorV2Themed SCXW8584375 BCX2">MultiMedia</span><span class="NormalTextRun SCXW8584375 BCX2"> Lab (</span><span class="NormalTextRun SpellingErrorV2Themed SCXW8584375 BCX2">MMLab</span><span class="NormalTextRun SCXW8584375 BCX2">) at the Chinese University of Hong Kong, working with Xiangyu Yue. His research focuses on universal representation learning, learning from limited supervision, and 3D-aware visual understanding. His work received several awards including Best Paper Award Finalist at CVPR 2022, BMVA Sullivan Doctoral Thesis Prize (Runner-Up)</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW8584375 BCX2">, Best</span><span class="NormalTextRun SCXW8584375 BCX2"> Paper Award at ICIG2017.</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW8584375 BCX2">
<ol class="NumberListStyle1 SCXW8584375 BCX2" role="list" start="2">
<li class="OutlineElement Ltr SCXW8584375 BCX2" style="display: block; margin-left: 24px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="41" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">Upcoming seminars for this term (save the dates):</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">19 Nov 2025</span></span><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">, Kostas </span><span class="NormalTextRun SpellingErrorV2Themed SCXW8584375 BCX2">Sechidis</span><span class="NormalTextRun SCXW8584375 BCX2"> (Novartis)</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">26 Nov 2025</span></span><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">, Xiyue Zhang (School of Computer Science, University of Bristol)</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">10 Dec 2025</span></span><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">, Michael Rule (School of Engineering Mathematics and Technology, University of Bristol)</span></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8584375 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8584375 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8584375 BCX2" lang="EN-US" style="font-size: 12pt; font-style: italic; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8584375 BCX2">Titles and abstracts to </span><span class="NormalTextRun SCXW8584375 BCX2">follow. </span></span><span class="LineBreakBlob BlobObject DragDrop SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;"><span class="SCXW8584375 BCX2">&nbsp;</span><br class="SCXW8584375 BCX2"></span><span class="EOP SCXW8584375 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
</div>
</div><br><br><b>Conception X 2026 – applications are now open</b><br><div id="WACViewPanel_ClipboardElement" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0" contenteditable="false" spellcheck="false">
<div class="OutlineElement Ltr SCXW203208263 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW203208263 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW203208263 BCX2">Conception X is hosting an online Discovery Session on </span></span><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW203208263 BCX2">30 October</span></span><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW203208263 BCX2"> for PhD students, postdocs and early-career researchers interested in </span><span class="NormalTextRun SpellingErrorV2Themed SCXW203208263 BCX2">commercialising</span><span class="NormalTextRun SCXW203208263 BCX2"> their research.</span></span><span class="EOP SCXW203208263 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW203208263 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW203208263 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; font-style: normal; text-decoration: none; font-variant: normal; text-transform: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW203208263 BCX2">Interested students can </span></span><a class="Hyperlink SCXW203208263 BCX2" style="text-decoration: none; color: inherit;" href="http://fslink.conceptionx.org/email/track/click?hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7Im11c3RoIjoiaHR0cHM6Ly9iaXQubHkvNDdhYWg0ciIsImxpb24iOiIzYTQ1ZiIsImdvcmlsbGEiOiIzODBmZDY2Y2YiLCJ0aWdlciI6ImZzbGluay5jb25jZXB0aW9ueC5vcmcifSwiaWF0IjoxNzYwNjEwOTU2fQ.l74if9HffP-I7J6t3Zsdmej5N_twX_suGL61ltjHpLE~eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImhvcnNlIjoic3V6YW5uZS5iaW5kaW5nQGJyaXN0b2wuYWMudWsiLCJjYW1lbCI6IjM4Nzc0YzEwYSJ9LCJpYXQiOjE3NjA2MTA5NTZ9.4K_njEJe1rdVMy8FA2pn6sj-Xt9Vvp9IEDep4gHedIo" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW203208263 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW203208263 BCX2" data-ccp-charstyle="Hyperlink">join a Discovery Session</span></span></a><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; font-style: normal; text-decoration: none; font-variant: normal; text-transform: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW203208263 BCX2"> to learn </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW203208263 BCX2">more, </span></span><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: rgb(31, 31, 31); font-size: 12pt; font-style: normal; text-decoration: none; font-variant: normal; text-transform: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW203208263 BCX2">or</span><span class="NormalTextRun SCXW203208263 BCX2"> can apply via the </span></span><a class="Hyperlink SCXW203208263 BCX2" style="text-decoration: none; color: inherit;" href="http://fslink.conceptionx.org/email/track/click?hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7Im11c3RoIjoiaHR0cHM6Ly9iaXQubHkvNG5Xd3Q5bCIsImxpb24iOiIzYTQ1ZiIsImdvcmlsbGEiOiIzODBmZDY2Y2YiLCJ0aWdlciI6ImZzbGluay5jb25jZXB0aW9ueC5vcmcifSwiaWF0IjoxNzYwNjEwOTU2fQ.RKZPxJ9JDqXLB3nGluRPovwgwD2Bae3x3CNVNbXwKN4~eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImhvcnNlIjoic3V6YW5uZS5iaW5kaW5nQGJyaXN0b2wuYWMudWsiLCJjYW1lbCI6IjM4Nzc0YzEwYSJ9LCJpYXQiOjE3NjA2MTA5NTZ9.4K_njEJe1rdVMy8FA2pn6sj-Xt9Vvp9IEDep4gHedIo" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW203208263 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW203208263 BCX2">Conception X website</span></span></a><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: rgb(31, 31, 31); font-size: 12pt; font-style: normal; text-decoration: none; font-variant: normal; text-transform: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW203208263 BCX2"> when ready. </span></span><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: rgb(31, 31, 31); font-size: 12pt; font-style: normal; text-decoration: none; font-variant: normal; text-transform: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW203208263 BCX2">Deadline: 16 December 2025</span></span><span class="TextRun SCXW203208263 BCX2" lang="EN-US" style="color: rgb(31, 31, 31); font-size: 12pt; font-style: normal; text-decoration: none; font-variant: normal; text-transform: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW203208263 BCX2">.</span></span><span class="EOP SCXW203208263 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(31, 31, 31);" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW203208263 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW203208263 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="EOP SCXW203208263 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(5, 99, 193);" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
</div><br><br><b>Digital Health Seminar Series</b><br><div id="WACViewPanel_ClipboardElement" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0" contenteditable="false" spellcheck="false">
<div class="SCXW165618624 BCX2">
<div class="ListContainerWrapper SCXW165618624 BCX2">
<ol class="NumberListStyle1 SCXW165618624 BCX2" role="list" start="1">
<li class="OutlineElement Ltr SCXW165618624 BCX2" style="display: block; margin-left: 24px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="2" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW165618624 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW165618624 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW165618624 BCX2">Darren Scott</span><span class="NormalTextRun SCXW165618624 BCX2">: Making the House a Home for Habits: Components and Characteristics for Home-Based Exercise Snacking</span></span><span class="EOP SCXW165618624 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(0, 0, 0);" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW165618624 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW165618624 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW165618624 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW165618624 BCX2">Location: </span></span><span class="TextRun SCXW165618624 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW165618624 BCX2">In Person AIMS Seminar Room 1 (University of Bristol only) &amp; Online (Link coming shortly)</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW165618624 BCX2" style="font-size: 12pt; line-height: 19px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(0, 0, 0);"><span class="SCXW165618624 BCX2">&nbsp;</span><br class="SCXW165618624 BCX2"></span><span class="TextRun SCXW165618624 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW165618624 BCX2">Date: </span></span><span class="TextRun SCXW165618624 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW165618624 BCX2">28 October 2025 14:00-15:00&nbsp;</span></span><span class="EOP SCXW165618624 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(0, 0, 0);" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW165618624 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW165618624 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW165618624 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW165618624 BCX2">Abstract: </span></span><span class="TextRun SCXW165618624 BCX2" lang="EN-US" style="color: rgb(0, 0, 0); font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW165618624 BCX2">There is a societal crisis taking place around the limited exercise we fit into our daily lives. A potential solution to this is exercise snacking, the concept of fitting much smaller exercises into much smaller windows, typically within the home in flow of other duties. There is currently limited technical exploration of how to integrate these exercises, which we </span><span class="NormalTextRun SCXW165618624 BCX2">sought</span><span class="NormalTextRun SCXW165618624 BCX2"> to resolve through a six-workshop series. The first three workshops looked at how to </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW165618624 BCX2">design for</span> <span class="NormalTextRun SCXW165618624 BCX2">different groups</span><span class="NormalTextRun SCXW165618624 BCX2"> and environments, and how these considerations may manifest in both new and evolving designs. The latter three workshops looked at low-fidelity prototypes, gaining some insights into preferred modalities as well as how they may work alongside necessary considerations such as existing routines and co-habitants.</span></span><span class="EOP SCXW165618624 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(0, 0, 0);" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
</div>
</div><br><br><b>Turing Seminar Series</b><br><div id="WACViewPanel_ClipboardElement" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0" contenteditable="false" spellcheck="false">
<div class="SCXW8862755 BCX2">
<div class="ListContainerWrapper SCXW8862755 BCX2">
<ol class="NumberListStyle1 SCXW8862755 BCX2" role="list" start="1">
<li class="OutlineElement Ltr SCXW8862755 BCX2" style="display: block; margin-left: 24px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="40" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><a class="Hyperlink SCXW8862755 BCX2" style="text-decoration: none; color: inherit;" href="https://www.bristol.ac.uk/golding/turing-institute/events-and-opportunities/turing-seminar-series/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW8862755 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; text-decoration: underline; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW8862755 BCX2" data-ccp-charstyle="Hyperlink">Peter Tennant: Have DAGs fulfilled their promise in epidemiology and health research?</span></span></a><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">&nbsp;</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Date: </span></span><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">22 October 13:00 &ndash; 14:00</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Location: </span></span><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Queens Building, 1.18LT</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
</div>
<div class="SCXW8862755 BCX2">
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Abstract:</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;"><span class="SCXW8862755 BCX2">&nbsp;</span><br class="SCXW8862755 BCX2"></span><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Causal directed acyclic graphs (DAGs) are among the most widely used causal diagrams. Developed in the 1980s and 1990s, with intellectual roots extending back to the 1920s, DAGs have become a core part of the modern data scientist&rsquo;s toolkit for planning and interpreting causal analyses of observational data. Advocates argue that DAGs improve the quality of causal research by increasing transparency and clarifying common analytical pitfalls. Critics, however, question whether these benefits have truly materialized, pointing to a persistent gap between theoretical promise and real-world practice.</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">At the 2024 World Congress of Epidemiology, Dr Peter Tennant (University of Leeds) and Prof Margarita Moreno Betancur (University of Melbourne) took part in a debate on whether DAGs have fulfilled their promise in epidemiology. In this talk, Dr Tennant will revisit the key arguments from that debate and share further reflections on how DAGs can be used more effectively in epidemiology and health research.</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW8862755 BCX2">
<ol class="NumberListStyle1 SCXW8862755 BCX2" role="list" start="2">
<li class="OutlineElement Ltr SCXW8862755 BCX2" style="display: block; margin-left: 24px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="40" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><a class="Hyperlink SCXW8862755 BCX2" style="text-decoration: none; color: inherit;" href="https://www.bristol.ac.uk/golding/turing-institute/events-and-opportunities/turing-seminar-series/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW8862755 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; text-decoration: underline; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW8862755 BCX2" data-ccp-charstyle="Hyperlink">Giovanni Petri: Tracing the Cultural Fabric of Sperm Whale Societies</span></span></a><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">&nbsp;</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Date: </span></span><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">5 November 13:00 &ndash; 14:00</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Location: </span></span><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Biomedical Building, C42</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Abstract:</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">Sperm whales live in highly structured societies where communication and cooperation intertwine in complex ways. </span></span><span class="LineBreakBlob BlobObject DragDrop SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;"><span class="SCXW8862755 BCX2">&nbsp;</span><br class="SCXW8862755 BCX2"></span><span class="TextRun SCXW8862755 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW8862755 BCX2">In this talk, I will explore how these two social dimensions &mdash;vocal culture and collective </span><span class="NormalTextRun SpellingErrorV2Themed SCXW8862755 BCX2">behaviour</span><span class="NormalTextRun SCXW8862755 BCX2">&mdash; interact within sperm whale societies</span><span class="NormalTextRun SCXW8862755 BCX2">.&nbsp; </span><span class="NormalTextRun SCXW8862755 BCX2">By combining large-scale acoustic datasets from the Pacific and Atlantic with computational models of coda structure, we uncover evidence that sperm whales not only share clan-specific repertoires but also learn aspects of vocal style from </span><span class="NormalTextRun SpellingErrorV2Themed SCXW8862755 BCX2">neighbouring</span><span class="NormalTextRun SCXW8862755 BCX2"> clans. This suggests that cultural boundaries are porous, </span><span class="NormalTextRun SCXW8862755 BCX2">maintained</span><span class="NormalTextRun SCXW8862755 BCX2"> by identity but shaped by interaction, and calls for an expanded notion of vocal identity that includes both repertoire and stylistic nuance. I will then turn to the social context in which such learning occurs: the cooperative dynamics of sperm whale groups. Using high-resolution drone footage, we reconstructed the collective </span><span class="NormalTextRun SpellingErrorV2Themed SCXW8862755 BCX2">behaviour</span><span class="NormalTextRun SCXW8862755 BCX2"> surrounding the first documented sperm whale birth in over forty years. The event revealed a tightly coordinated network of </span><span class="NormalTextRun SCXW8862755 BCX2">assistance</span><span class="NormalTextRun SCXW8862755 BCX2"> across kinship lines, where all members </span><span class="NormalTextRun SCXW8862755 BCX2">participated</span><span class="NormalTextRun SCXW8862755 BCX2"> in protecting and lifting the negatively buoyant new-born. Together, these results suggest that sperm whale societies sustain a form of collective intelligence rooted in shared learning and cooperative care&mdash;one where communication and cooperation co-evolve as coupled substrates of culture.</span></span><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW8862755 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW8862755 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="EOP SCXW8862755 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
</div>
</div><br><br><b>Bristol Doctoral College (BDC) Events and Opportunities</b><br><div id="WACViewPanel_ClipboardElement" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0" contenteditable="false" spellcheck="false">
<div class="SCXW30883839 BCX2">
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ol class="NumberListStyle1 SCXW30883839 BCX2" role="list" start="1">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 24px; font-size: 11pt; font-family: Calibri, 'Calibri_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="" data-listid="8" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2">BDC&rsquo;s November and December Personal &amp; Professional Development (PPD) workshops are now open for bookings!&nbsp;</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(5, 99, 193);" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:720,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;335559991&quot;:360}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW30883839 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Why Join</span><span class="NormalTextRun SCXW30883839 BCX2">?&nbsp;</span> <span class="NormalTextRun SCXW30883839 BCX2">Whether </span><span class="NormalTextRun SCXW30883839 BCX2">you're</span><span class="NormalTextRun SCXW30883839 BCX2"> just starting out or preparing to share your work with the world, these sessions are designed to support you in making real progress in your research and career</span><span class="NormalTextRun SCXW30883839 BCX2">.&nbsp; </span><span class="NormalTextRun SCXW30883839 BCX2">Just choose the sessions that fit your goals and schedule.</span><span class="NormalTextRun SCXW30883839 BCX2"> More information can be found on the </span></span><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://www.bristol.ac.uk/doctoral-college/ppd/pgr-essentials-/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; text-decoration: underline; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">BDC webpage</span></span></a><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">.&nbsp;</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{&quot;335559685&quot;:720}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ul class="BulletListStyle1 SCXW30883839 BCX2" role="list">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 48px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="47" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:1080,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Recommended for Early-Stage PGRs</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ul class="BulletListStyle1 SCXW30883839 BCX2" role="list">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 72px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Wingdings" data-listid="48" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:1440,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Wingdings&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;multilevel&quot;,&quot;469778510&quot;:&quot;bullet&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=6417e7b410&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">Developing an Effective Relationship with Your Supervisor</span></span></a><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 11pt; line-height: 19.425px; font-family: WordVisiCarriageReturn_MSFontService, Calibri, 'Calibri_EmbeddedFont', 'Calibri_MSFontService', sans-serif;"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">5 November, </span><span class="NormalTextRun SCXW30883839 BCX2">14:00</span><span class="NormalTextRun SCXW30883839 BCX2"> to </span><span class="NormalTextRun SCXW30883839 BCX2">17:00</span><span class="NormalTextRun SCXW30883839 BCX2"> (Online)&nbsp;</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW30883839 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 96px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Build strong, collaborative relationships with strategies that support clear communication and shared expectations</span></span><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: 'Helvetica', 'Helvetica_EmbeddedFont', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">.</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: 'Helvetica', 'Helvetica_EmbeddedFont', sans-serif; color: windowtext;" data-ccp-props="{&quot;335559685&quot;:1440}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ul class="BulletListStyle1 SCXW30883839 BCX2" role="list">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 72px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Wingdings" data-listid="48" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:1440,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Wingdings&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;multilevel&quot;,&quot;469778510&quot;:&quot;bullet&quot;}" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=0734acbf42&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">Turbo Charge Your Writing</span></span></a><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 11pt; line-height: 19.425px; font-family: WordVisiCarriageReturn_MSFontService, Calibri, 'Calibri_EmbeddedFont', 'Calibri_MSFontService', sans-serif;"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">13 November, 9:30 am to 12</span><span class="NormalTextRun SCXW30883839 BCX2">:00 </span><span class="NormalTextRun SCXW30883839 BCX2">(Online)&nbsp;</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:1440,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259,&quot;335559991&quot;:360}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW30883839 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 96px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Learn practical techniques to boost your writing productivity and reduce the stress of getting started.</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:1440,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ul class="BulletListStyle1 SCXW30883839 BCX2" role="list">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 72px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Wingdings" data-listid="48" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:1440,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Wingdings&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;multilevel&quot;,&quot;469778510&quot;:&quot;bullet&quot;}" data-aria-posinset="3" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: none; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2">Work Smarter not Harder: File Management, Open Access &amp; Copyright (Hybrid)</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(0, 124, 137);"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">26 November, 1</span><span class="NormalTextRun SCXW30883839 BCX2">3:00</span><span class="NormalTextRun SCXW30883839 BCX2"> to </span><span class="NormalTextRun SCXW30883839 BCX2">16:00</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=e9beae941e&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">Online</span></span></a><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 11pt; line-height: 19.425px; font-family: WordVisiCarriageReturn_MSFontService, Calibri, 'Calibri_EmbeddedFont', 'Calibri_MSFontService', sans-serif;"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=4cc00fc86a&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">In-person</span></span></a><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:1440,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:259,&quot;335559991&quot;:360}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW30883839 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 96px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Set up systems that save time and support good research practice from the start.</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:1440,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ul class="BulletListStyle1 SCXW30883839 BCX2" role="list">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 48px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="47" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:1080,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Recommended for Mid to Late Stage PGRs</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{}">&nbsp;</span></p>
</li>
</ul>
</div>
</div>
<div class="SCXW30883839 BCX2">
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ul class="BulletListStyle1 SCXW30883839 BCX2" role="list">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 72px; font-size: 11pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Wingdings" data-listid="49" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:1440,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Wingdings&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;multilevel&quot;,&quot;469778510&quot;:&quot;bullet&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: none; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2">Perfect Posters (Hybrid)</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(0, 124, 137);"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">3 November, </span><span class="NormalTextRun SCXW30883839 BCX2">14:00</span><span class="NormalTextRun SCXW30883839 BCX2"> to </span><span class="NormalTextRun SCXW30883839 BCX2">16:00</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=9155f14a28&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">Online</span></span></a><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 11pt; line-height: 19.425px; font-family: WordVisiCarriageReturn_MSFontService, Calibri, 'Calibri_EmbeddedFont', 'Calibri_MSFontService', sans-serif;"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=4c1df323f2&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">In-person</span></span></a><span class="EOP SCXW30883839 BCX2" style="font-size: 11pt; line-height: 19.425px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif;" data-ccp-props="{}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW30883839 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 96px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Design posters that communicate your research clearly and attract attention at conferences.</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:1440,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ul class="BulletListStyle1 SCXW30883839 BCX2" role="list">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 72px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Wingdings" data-listid="49" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:1440,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Wingdings&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;multilevel&quot;,&quot;469778510&quot;:&quot;bullet&quot;}" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=e73ea07a1f&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">Presenting Your Research</span></span></a><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 11pt; line-height: 19.425px; font-family: WordVisiCarriageReturn_MSFontService, Calibri, 'Calibri_EmbeddedFont', 'Calibri_MSFontService', sans-serif;"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">12 November, 13:00 to 16:00 (Face&ndash;to&ndash;face)&nbsp;</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW30883839 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 96px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Strengthen your presentation skills and learn how to engage different audiences with confidence. [</span><span class="NormalTextRun SCXW30883839 BCX2">Recommended if you plan to take part in next year's </span></span><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=79c22df673&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">3MT</span></span></a><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2"> competition!</span><span class="NormalTextRun SCXW30883839 BCX2">]</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:1440,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW30883839 BCX2">
<ul class="BulletListStyle1 SCXW30883839 BCX2" role="list">
<li class="OutlineElement Ltr SCXW30883839 BCX2" style="display: block; margin-left: 72px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Wingdings" data-listid="49" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:1440,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Wingdings&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;multilevel&quot;,&quot;469778510&quot;:&quot;bullet&quot;}" data-aria-posinset="3" data-aria-level="1">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><a class="Hyperlink SCXW30883839 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=ef3ba0d79f&amp;e=25eef21eff" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW30883839 BCX2" lang="EN-US" style="color: rgb(0, 124, 137); font-size: 12pt; font-style: normal; text-decoration: underline; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW30883839 BCX2" data-ccp-charstyle="Hyperlink">How to Be an Inclusive Researcher</span></span></a><span class="LineBreakBlob BlobObject DragDrop SCXW30883839 BCX2" style="font-size: 11pt; line-height: 19.425px; font-family: WordVisiCarriageReturn_MSFontService, Calibri, 'Calibri_EmbeddedFont', 'Calibri_MSFontService', sans-serif;"><span class="SCXW30883839 BCX2">&nbsp;</span><br class="SCXW30883839 BCX2"></span><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Thursday 20 November, 10 am to 1 pm (Face-to-face)&nbsp;</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW30883839 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 96px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW30883839 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: normal; font-variant: normal; text-transform: none; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW30883839 BCX2">Explore inclusive research practices that enhance the quality and relevance of your work.</span></span><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.5042px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:1440,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW30883839 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW30883839 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: -24px;"><span class="EOP SCXW30883839 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(5, 99, 193);" data-ccp-props="{&quot;134233117&quot;:false,&quot;134233118&quot;:false,&quot;201341983&quot;:0,&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559685&quot;:720,&quot;335559737&quot;:0,&quot;335559738&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;335559991&quot;:360}">&nbsp;</span></p>
</div>
</div>
</div><br><br><b>Reference management: EndNote Online – organiser: Library - Subject Support</b><br><div id="WACViewPanel_ClipboardElement" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0" contenteditable="false" spellcheck="false">
<div class="SCXW138186388 BCX2">
<div class="OutlineElement Ltr SCXW138186388 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW138186388 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">Date: </span></span><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">20 October 14:00 &ndash; 15:00 (Online)</span></span><span class="EOP SCXW138186388 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW138186388 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW138186388 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">EndNote Online is a reference management software package that lets you gather and </span><span class="NormalTextRun SpellingErrorV2Themed SCXW138186388 BCX2">organise</span><span class="NormalTextRun SCXW138186388 BCX2"> references, then cite them in various word processors whilst automatically creating a bibliography.</span></span><span class="EOP SCXW138186388 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW138186388 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW138186388 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">By the end of this introductory </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW138186388 BCX2">workshop</span><span class="NormalTextRun SCXW138186388 BCX2"> you will be able to:</span></span><span class="EOP SCXW138186388 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW138186388 BCX2">
<ul class="BulletListStyle1 SCXW138186388 BCX2" role="list">
<li class="OutlineElement Ltr SCXW138186388 BCX2" style="display: block; margin-left: 24px; font-size: 11pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="46" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW138186388 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">import references to EndNote</span></span><span class="EOP SCXW138186388 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</li>
</ul>
</div>
</div>
<div class="SCXW138186388 BCX2">
<div class="ListContainerWrapper SCXW138186388 BCX2">
<ul class="BulletListStyle1 SCXW138186388 BCX2" role="list">
<li class="OutlineElement Ltr SCXW138186388 BCX2" style="display: block; margin-left: 24px; font-size: 11pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="46" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW138186388 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">manually enter references</span></span><span class="EOP SCXW138186388 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="ListContainerWrapper SCXW138186388 BCX2">
<ul class="BulletListStyle1 SCXW138186388 BCX2" role="list">
<li class="OutlineElement Ltr SCXW138186388 BCX2" style="display: block; margin-left: 24px; font-size: 11pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="46" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="3" data-aria-level="1">
<p class="Paragraph SCXW138186388 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">search your EndNote library for specific references and </span><span class="NormalTextRun SpellingErrorV2Themed SCXW138186388 BCX2">organise</span><span class="NormalTextRun SCXW138186388 BCX2"> them with groups</span></span><span class="EOP SCXW138186388 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="ListContainerWrapper SCXW138186388 BCX2">
<ul class="BulletListStyle1 SCXW138186388 BCX2" role="list">
<li class="OutlineElement Ltr SCXW138186388 BCX2" style="display: block; margin-left: 24px; font-size: 11pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="46" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="4" data-aria-level="1">
<p class="Paragraph SCXW138186388 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">cite and edit references in MS Word.</span></span><span class="EOP SCXW138186388 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW138186388 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW138186388 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><a class="Hyperlink SCXW138186388 BCX2" style="text-decoration: none; color: inherit;" href="https://www.bristol.ac.uk/students/life-in-bristol/campus/events/calendar/#event=78121149;instance=20251020140000?popup=1&amp;lang=en-UK" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW138186388 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; text-decoration: underline; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW138186388 BCX2" data-ccp-charstyle="Hyperlink">Book your place here.</span></span></a><span class="TextRun SCXW138186388 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW138186388 BCX2">&nbsp;</span></span><span class="EOP SCXW138186388 BCX2" style="font-size: 12pt; line-height: 19px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
</div>
</div>
</div><br><br><b>Around Bristol</b><br><div id="WACViewPanel_ClipboardElement" class="WACEditing EditMode EditingSurfaceBody FireFox WACViewPanel_DisableLegacyKeyCodeAndCharCode usehover" style="overflow: hidden; visibility: visible; direction: ltr;" tabindex="0" contenteditable="false" spellcheck="false">
<div class="SCXW197898906 BCX2">
<div class="ListContainerWrapper SCXW197898906 BCX2">
<ol class="NumberListStyle1 SCXW197898906 BCX2" role="list" start="1">
<li class="OutlineElement Ltr SCXW197898906 BCX2" style="display: block; margin-left: 24px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="45" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW197898906 BCX2">Helios at Bristol Cathedral</span></span><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(5, 99, 193);" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW197898906 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">Date: </span></span><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">06 October &ndash; 02 November</span></span><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW197898906 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">Location</span></span><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">: Bristol Cathedral, College Green, BS1 5TJ</span></span><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW197898906 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">Helios is a seven-</span><span class="NormalTextRun SpellingErrorV2Themed SCXW197898906 BCX2">metre</span><span class="NormalTextRun SCXW197898906 BCX2"> internally illuminated sphere that brings the sun&rsquo;s intricate details into view. Created at a scale of 1:200 million, each </span><span class="NormalTextRun SpellingErrorV2Themed SCXW197898906 BCX2">centimetre</span><span class="NormalTextRun SCXW197898906 BCX2"> of the sculpture </span><span class="NormalTextRun SCXW197898906 BCX2">represents</span><span class="NormalTextRun SCXW197898906 BCX2"> 2,000 km of the sun&rsquo;s surface. Visitors can explore sunspots, filaments, and solar flares&mdash;features that are usually millions of miles away&mdash;safely </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW197898906 BCX2">and up</span><span class="NormalTextRun SCXW197898906 BCX2"> close. </span></span><a class="Hyperlink SCXW197898906 BCX2" style="text-decoration: none; color: inherit;" href="https://bristol-cathedral.co.uk/event/bft-presents-helios-at-bristol-cathedral-2/2025-10-06/1/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW197898906 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; text-decoration: underline; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW197898906 BCX2" data-ccp-charstyle="Hyperlink">Read more.</span></span></a><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">&nbsp;</span></span><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW197898906 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; font-style: italic; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">Admission: Entry by donation | No booking </span><span class="NormalTextRun SCXW197898906 BCX2">required</span></span><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW197898906 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW197898906 BCX2">
<ol class="NumberListStyle1 SCXW197898906 BCX2" role="list" start="2">
<li class="OutlineElement Ltr SCXW197898906 BCX2" style="display: block; margin-left: 24px; font-size: 12pt; font-family: Aptos, 'Aptos_MSFontService', sans-serif; vertical-align: baseline; direction: ltr;" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="45" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: rgb(5, 99, 193); font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW197898906 BCX2">Black Beauty at The Island Gallery</span></span><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: rgb(5, 99, 193);" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="OutlineElement Ltr SCXW197898906 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">Date: </span></span><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">24 October 19:00 &ndash; 22:00, 25 October 12:00 &ndash; 17:00</span></span><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW197898906 BCX2" style="direction: ltr;">
<p class="Paragraph SCXW197898906 BCX2" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin: 0px 0px 0px 48px; padding-left: 0px; padding-right: 0px; text-indent: 0px;"><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: bold;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">Location</span></span><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">: The Island Gallery, Bridewell Street, Bristol. BS1 2QD</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: WordVisiCarriageReturn_MSFontService, Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;"><span class="SCXW197898906 BCX2">&nbsp;</span><br class="SCXW197898906 BCX2"></span><span class="TextRun SCXW197898906 BCX2" lang="EN-US" style="color: windowtext; font-size: 12pt; text-decoration: none; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; font-weight: normal;" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW197898906 BCX2">Local legend Jennie Cave presents a collection of new photo montages celebrating black beauty, </span><span class="NormalTextRun SCXW197898906 BCX2">culture</span><span class="NormalTextRun SCXW197898906 BCX2"> and community.</span> <span class="NormalTextRun SCXW197898906 BCX2">Through retro-surreal collage, Cave reimagines Black identity, joy and cultural heritage using bold visuals drawn from vintage photography and ephemera</span><span class="NormalTextRun SCXW197898906 BCX2">.&nbsp;</span></span><span class="EOP SCXW197898906 BCX2" style="font-size: 12pt; line-height: 20.3458px; font-family: Aptos, 'Aptos_EmbeddedFont', 'Aptos_MSFontService', sans-serif; color: windowtext;" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
</div>
</div><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b>Reference management: EndNote Online – organiser: Library - Subject Support - 2025-10-20</b><br><b>Digital Health Seminar Series - 2025-10-28</b><br><b>Conception X 2026 – applications are now open - 2025-10-30</b><br>