---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 19-06-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p><span style="color: rgb(0, 0, 0);">Around Bristol</span></p></li><li><p>Move date and info for Temple Quarter</p></li><li><p>CDT AI Lunch and Learn Seminar</p></li><li><p>Opportunities from the Turing University Network</p></li><li><p>Digital Health Seminar Series</p></li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b><p><span style="color: rgb(0, 0, 0);">Around Bristol</span></p></b><br><div><strong data-olk-copy-source="MailCompose">Key Pride events</strong></div>
<div>
<ul>
<li>19 June: Launch party, Wake the Tiger</li>
<li><span class="T286Pc" data-sfc-cp="" data-sfc-root="c" data-sfc-cb="" data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 400; margin: 0px; text-decoration: none; border-bottom: 0px rgb(10, 10, 10);"><span class="Yjhzub">2 July:<!--TgQPHd||[]--></span> Pride Circus Night, Circomedia.</span></li>
<li><span class="T286Pc" data-sfc-cp="" data-sfc-root="c" data-sfc-cb="" data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 400; margin: 0px; text-decoration: none; border-bottom: 0px rgb(10, 10, 10);"><!--TgQPHd||[]--></span><!--TgQPHd||[]--><span class="T286Pc" data-sfc-cp="" data-sfc-root="c" data-sfc-cb="" data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 400; margin: 0px; text-decoration: none; border-bottom: 0px rgb(10, 10, 10);"><span class="Yjhzub">3 July&nbsp;</span><span class="iNLQDb" data-sfc-cp="" data-sfc-root="c" data-sfc-cb="" data-sfc-inited="2" data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 400; margin: 0px; text-decoration: none; border-bottom: 0px rgb(10, 10, 10);"><span class="qNqJIe" data-sfc-cp="" data-sfc-root="c" data-sfc-cb="" data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 500; margin: 0px; text-decoration: underline 1px rgb(26, 13, 171); border-bottom: 0px rgb(26, 13, 171);"><a class="qNqJIe" href="https://bristolbeacon.org/whats-on/bristol-pride-ceilidh-2026/" target="_blank" rel="noopener" data-hveid="CAIIAAgACBMQBg" aria-label="⁠Bristol Pride Ceilidh. Link preview. Site: Bristol Beacon. Title: Bristol Pride Ceilidh. URL: https://bristolbeacon.org/whats-on/bristol-pride-ceilidh-2026/." data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 500; margin: 0px; text-decoration: underline 1px rgb(26, 13, 171); border-bottom: 0px rgb(26, 13, 171);">Bristol Pride Ceilidh,</a></span></span> Lantern Hall, Bristol Beacon, featuring inclusive dancing for all skill levels.</span></li>
<li><span class="T286Pc" data-sfc-cp="" data-sfc-root="c" data-sfc-cb="" data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 400; margin: 0px; text-decoration: none; border-bottom: 0px rgb(10, 10, 10);"><!--TgQPHd||[]--></span><!--TgQPHd||[]--><span class="T286Pc" data-sfc-cp="" data-sfc-root="c" data-sfc-cb="" data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 400; margin: 0px; text-decoration: none; border-bottom: 0px rgb(10, 10, 10);"><span class="Yjhzub">4 July:<!--TgQPHd||[]--></span> Pride Dog Show, Castle Park</span></li>
<li><span class="T286Pc" data-sfc-cp="" data-sfc-root="c" data-sfc-cb="" data-copy-service-computed-style="font-family: &quot;Google Sans&quot;, Arial, sans-serif; font-size: 16px; font-weight: 400; margin: 0px; text-decoration: none; border-bottom: 0px rgb(10, 10, 10);">11 July: Pride Day, The Downs</span></li>
</ul>
</div>
<div>https://bristolpride.co.uk/</div>
<div>&nbsp;</div>
<p>&nbsp;</p><br><br><b><p>Move date and info for Temple Quarter</p></b><br><p>For those of us moving to Temple Quarter, an email has been sent out earlier this week with confirmation of the move. Please have a read and sign up for a Temple Quarter induction tour.</p>
<p>To make the move as stress-free(!) and efficient as possible please could you do the following:</p>
<ul>
<li>Sort out any personal items in 1CS <strong>by the 24 July </strong>at the latest. If you have not booked a crate, then you will have to deal with transportation yourself.</li>
<li>If you have any plants in 1CS then you can either take home or they will be transported carefully to TQ. Please name label your plant if you are especially attached to it.</li>
<li>Don't forget to clear out your locker by July 24 and leave the key in the lock - it will be difficult to get any items back once we have moved.</li>
<li>Please don't remove any docking stands or monitors on the desks as they belong to the Faculty and will be collected after the move.</li>
</ul>
<p>&nbsp;</p><br><br><b><p>CDT AI Lunch and Learn Seminar</p></b><br><div class="x_elementToProof" data-olk-copy-source="MessageBody">Please save the date for our next CDT AI Lunch and Learn Seminar as follows:</div>
<div>&nbsp;</div>
<div>Date: Wednesday 24 June</div>
<div class="x_elementToProof">Location: SM2, Ada Lovelace Building</div>
<div class="x_elementToProof">Time: 1:30 - 3pm</div>
<div class="x_elementToProof">Speaker:&nbsp;<a title="https://faculty.engineering.ucdavis.edu/davidson/" href="https://faculty.engineering.ucdavis.edu/davidson/" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" data-linkindex="0">Professor Ian Davidson</a>, University of California</div>
<div class="x_elementToProof">Talk Title/abstract: Details to follow</div>
<div class="x_elementToProof">&nbsp;</div>
<div class="x_elementToProof">We will have pizza and the chance to network with colleagues from 1:30 followed by Ian's talk from 2 - 3pm</div><br><br><b><p>Opportunities from the Turing University Network</p></b><br><p><strong data-olk-copy-source="MessageBody">Alan Turing Institute&nbsp;</strong><strong>Data Study Groups</strong></p>
<p>We&rsquo;re excited to announce a brand-new recruitment process for our Data Study Groups (DSGs), designed to make it easier and more flexible than ever to get involved.</p>
<p>From now on, applications will be open on a rolling basis, meaning you can apply at any time throughout the year. Once you apply, our team will review your application and, if successful, you&rsquo;ll be invited to join our DSG participant pool.</p>
<p>As new DSG challenges arise, we&rsquo;ll match participants with opportunities that align with their skills, expertise and interests, and invite them to take part in the relevant event. While you&rsquo;re in the participant pool, you&rsquo;ll also receive updates on the latest Turing news, events and opportunities to connect with our community.</p>
<p>To learn more and submit your application,&nbsp;<a title="https://bit.ly/4eYbzoF" href="https://bit.ly/4eYbzoF" data-auth="NotApplicable" data-linkindex="0">please visit our website</a></p>
<p><strong><em><span data-olk-copy-source="MessageBody">1st Bath Summer School in Machine Learning, University of Bath, 05 - 07 August 2026, 09:00 &ndash; 16:00</span></em></strong></p>
<p><strong><em>&nbsp;</em></strong>University of Bath are pleased to announce the 1st Bath Summer School in Machine Learning, hosted by the Centre for Artificial Intelligence.</p>
<p>The school offers three days of tutorial-style lectures spanning core and emerging topics in machine learning, designed to help graduate students rapidly build knowledge outside their direct research focus &mdash; in a friendly, inclusive environment.</p>
<p>The school is open to PhD students, postdocs, and research staff at any UK or EU university. A solid foundational knowledge of machine learning is assumed. Participants must be available for the full three-day programme.</p>
<p>Further information, including costs, available <a title="https://www.bathmlsummerschool.org/" href="https://www.bathmlsummerschool.org/" data-auth="NotApplicable" data-linkindex="1">here</a></p><br><br><b><p>Digital Health Seminar Series</p></b><br><p><strong data-olk-copy-source="MessageBody">Topic: </strong>From Signals to Function: Measuring What Matters in Human Health</p>
<p><strong>Location:&nbsp;</strong>In Person at&nbsp;<a title="https://www.bristol.ac.uk/directory/learning-facilities/central-teaching-spaces/ada-lovelace-building/sm4/" href="https://www.bristol.ac.uk/directory/learning-facilities/central-teaching-spaces/ada-lovelace-building/sm4/" data-auth="NotApplicable" data-linkindex="0">Ada Lovelace Building SM4</a>&nbsp;(University of Bristol only) &amp; Online<strong><span lang="en-US" data-olk-copy-source="MessageBody">&nbsp;</span></strong><span lang="en-US"><a title="https://teams.microsoft.com/meet/339269592193575?p=QIXJtquejRBuEoBSfZ" href="https://teams.microsoft.com/meet/339269592193575?p=QIXJtquejRBuEoBSfZ" data-auth="NotApplicable" data-linkindex="4">https://teams.microsoft.com/meet/339269592193575?p=QIXJtquejRBuEoBSfZ</a></span></p>
<p><strong>Date:&nbsp;</strong>June 23,14:00-15:00 GMT</p>
<p><strong>Abstract:</strong><br>Modern healthcare relies on a wide range of measurements, from physiological signals to medical images. Yet understanding what these measurements reveal about tissue function remains a major challenge. In this talk, I will discuss how approaches that integrate signals, images and AI can be used to move beyond visual interpretation towards quantitative measures of tissue function.</p>
<p>Using examples from tissue perfusion estimation and vascular analysis, I will share how interdisciplinary collaborations have shaped my research and discuss opportunities for developing clinically meaningful biomarkers that improve our understanding of health and disease.</p>
<p><strong>&nbsp;</strong><strong>Bio:</strong></p>
<p>Dr Yi Yin is a Lecturer in Machine Learning for Health at the University of Bristol and an Honorary Research Fellow at the University of Oxford. She holds a PhD in Signal and Image Processing and has more than 10 years of experience in interdisciplinary research at the interface of engineering, AI and healthcare.</p>
<p>Prior to joining Bristol, she held research positions at INRIA Paris and the University of Oxford, where she worked on multi-modal medical image analysis, computer vision and AI for healthcare applications. Her research spans signal processing, medical imaging, machine learning and health data science, with interests in image analysis, quantitative imaging, healthcare AI and interdisciplinary innovation.</p><br><br><h2>Forthcoming Calendar of Events</h2><br><br>