---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 23-09-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p>Bristol Doctoral College - Opportunities</p></li><li><p>PGR Essential Resources</p></li><li><p>Summer PGR events</p></li><li><p>AI Hackathon - Applications now open</p></li><li><p><span style="font-size: 11.0pt; line-height: 107%; font-family: 'Aptos',sans-serif; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: Aptos; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: minor-latin; mso-bidi-font-family: 'Times New Roman'; mso-bidi-theme-font: minor-bidi; mso-ansi-language: EN-GB; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Paid AI and Data Support Opportunity for University of Bristol PhD Students</span></p></li><li><p>Welcome week!</p></li><li><p>BAIS 2026 (Summer School)</p></li><li><p><span data-olk-copy-source="MessageBody">Sloane Robinson Building - Current opening hours</span></p></li><li><p>Careers Service support for PGRs</p></li><li><p>Bristol Doctoral College (BDC) - events and workshops</p></li><li><p>Around Bristol</p></li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b><p>Bristol Doctoral College - Opportunities</p></b><br><h1 data-olk-copy-source="MessageBody">University Wide Language Programme</h1>
<p>Application deadline 14 July, 5 pm</p>
<p>Have you always wanted to learn a language or improve your foreign language skills? Join the University Wide Language Programme. All units begin in the first week of term and run for 22 sessions, with teaching delivered in small, in-person groups. Fees for PGRs are &pound;325 per unit.</p>
<p class="x_last-child"><a title="https://us.list-manage.com/wa1D1QihYfO?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/wa1D1QihYfO?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" data-auth="NotApplicable" data-linkindex="6">Find out more</a>&nbsp;and&nbsp;<a title="https://us.list-manage.com/102tkZ2LXSQ?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/102tkZ2LXSQ?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" data-auth="NotApplicable" data-linkindex="7">apply now</a>.</p>
<h1 data-olk-copy-source="MessageBody">Viva Survivor</h1>
<p>Wednesday 1 July, 10 am to 1 pm, online</p>
<p>The viva is almost the end of a research degree journey. A lot of work leads to this point, but often anxiety can mix with the sense of achievement at completing the thesis or dissertation. In this three-hour live webinar, you will learn:</p>
<ul>
<li>
<p>realistic expectations for the viva</p>
</li>
<li>
<p>identify key practical steps to take before submission</p>
</li>
<li>
<p>explore practical strategies for preparation and the day of the viva. &nbsp;</p>
</li>
</ul>
<p class="x_last-child"><a title="https://us.list-manage.com/DAgbv4_e3rm?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/DAgbv4_e3rm?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" data-auth="NotApplicable" data-linkindex="9">Find out more and book your place</a></p>
<h1 data-olk-copy-source="MessageBody">Enjoy summer events with the Global Lounge</h1>
<p>Staying In Bristol over the summer? Check out the Global Lounge&rsquo;s fun, friendly summer activities, they&rsquo;re free, open to all, and a great way to connect with other students.</p>
<p>You can enjoy a picnic in the park, take a tour of Bristol's top sights, enjoy fish and chips, celebrate at Global Fest, test your taste buds the Great British Snack Off and much more!</p>
<p class="x_last-child">Events run until 7 August.&nbsp;<a title="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=d3adbc909e&amp;e=f73c8a8ff3" href="https://bristol.us8.list-manage.com/track/click?u=30ee75cf2bd334380a7a25cd5&amp;id=d3adbc909e&amp;e=f73c8a8ff3" data-auth="NotApplicable" data-linkindex="23">Check out the Global Lounge website for details</a>.</p>
<p class="x_last-child">Head over to the&nbsp;<a title="https://us.list-manage.com/1CRcu3EaKQf?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/1CRcu3EaKQf?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" data-auth="NotApplicable" data-linkindex="24">BDC events calendar</a> for all our PGR events and workshops.</p><br><br><b><p>PGR Essential Resources</p></b><br><p><span style="font-size: 11.0pt; line-height: 107%; font-family: 'Aptos',sans-serif; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: Aptos; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: minor-latin; mso-bidi-font-family: 'Times New Roman'; mso-bidi-theme-font: minor-bidi; mso-ansi-language: EN-GB; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Bristol Doctoral College&rsquo;s LinkedIn Learning pathways are available 24/7, 365 days a year. They offer vital training that will help you navigate your research journey with confidence, from&nbsp;<a title="https://us.list-manage.com/9UqnlewFi3h?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/9UqnlewFi3h?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">intellectual property</a> and&nbsp;<a title="https://us.list-manage.com/xLY0Dm5yeq6?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/xLY0Dm5yeq6?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">research ethics</a>&nbsp;to&nbsp;<a title="https://us.list-manage.com/orbFD3uHJRm?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/orbFD3uHJRm?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">Viva preparation</a>,&nbsp;<a title="https://us.list-manage.com/ti8mXS2VQYG?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/ti8mXS2VQYG?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">funding</a>, and more</span></p><br><br><b><p>Summer PGR events</p></b><br><p class="MsoNormal"><strong>Writer&rsquo;s Retreat</strong></p>
<p class="MsoNormal"><strong>Wednesday 5 August</strong>, 9:30 am to 5 pm, PGR Hub &amp; online</p>
<p class="MsoNormal">Dedicate time to your writing in a supportive, distraction-free environment. Join our monthly writer's retreat for a full day of focused writing time, goal-setting, and the opportunity to connect with fellow postgraduate researchers.</p>
<p class="MsoNormal">Sign up to attend&nbsp;<a title="https://us.list-manage.com/aErTCRviNwB?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/aErTCRviNwB?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">in-person</a>&nbsp;or&nbsp;<a title="https://us.list-manage.com/atlIOIDwBuc?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/atlIOIDwBuc?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">online</a></p>
<p class="MsoNormal"><strong>PGR Film club</strong></p>
<p class="MsoNormal">The PGR Film Club wants to hear from you! Whether it's a recent favourite, a timeless classic, an overlooked gem, or a film you've always wanted to watch with others, we'd love your suggestions.</p>
<p class="MsoNormal">Help shape future screenings by sharing your recommendations via our online form:</p>
<p><span style="font-size: 11.0pt; line-height: 107%; font-family: 'Aptos',sans-serif; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: Aptos; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: minor-latin; mso-bidi-font-family: 'Times New Roman'; mso-bidi-theme-font: minor-bidi; mso-ansi-language: EN-GB; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><a title="https://us.list-manage.com/rfZ1ut9cRuF?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/rfZ1ut9cRuF?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">Submit your film recommendations</a></span></p><br><br><b><p>AI Hackathon - Applications now open</p></b><br><p class="MsoNormal">13&nbsp;- 14 August, UWE Bristol, Business School</p>
<p class="MsoNormal">Join an exciting cross-university AI Hackathon bringing together talented students, researchers, industry leaders and innovators to tackle real-world business challenges using Artificial Intelligence. You do not need to be an AI expert to apply.</p>
<p class="MsoNormal">This initiative is being led by Tech West England Advocates in collaboration with:</p>
<p class="MsoNormal">&bull; University of the West of England &ndash; UWE Bristol</p>
<p class="MsoNormal">&bull; University of Bristol</p>
<p class="MsoNormal"><a title="https://us.list-manage.com/drXvFPF5hjx?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/drXvFPF5hjx?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">Find out more and register</a></p><br><br><b><p><span style="font-size: 11.0pt; line-height: 107%; font-family: 'Aptos',sans-serif; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: Aptos; mso-fareast-theme-font: minor-latin; mso-hansi-theme-font: minor-latin; mso-bidi-font-family: 'Times New Roman'; mso-bidi-theme-font: minor-bidi; mso-ansi-language: EN-GB; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Paid AI and Data Support Opportunity for University of Bristol PhD Students</span></p></b><br><p class="MsoNormal">Application deadline Monday 10 August</p>
<p class="MsoNormal">The&nbsp;<a title="https://us.list-manage.com/TRr6fUXiKAF?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/TRr6fUXiKAF?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">Jean Golding Institute (JGI)</a>&nbsp;are recruiting a new team of PhD students for the Ask-JGI helpdesk to work from October 2026 until the end of September 2027!</p>
<p class="MsoNormal">The JGI offers a consultancy service to researchers through its Ask-JGI helpdesk, which provides one day of free support to all staff and doctoral students at the University of Bristol for queries relating to data science, AI and software engineering. The helpdesk is run by PhD students and supported by the JGI&rsquo;s own team of data scientists and research software engineers.</p>
<p class="MsoNormal">This is a paid opportunity at&nbsp;<a title="https://us.list-manage.com/13nxV2adXz9?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/13nxV2adXz9?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">Research Support Assistant Level 2</a>&nbsp;for PhD students.</p>
<p class="MsoNormal"><a title="https://us.list-manage.com/GanRDE11EkS?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/GanRDE11EkS?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">Visit the recruitment webpage</a>&nbsp;for full details of the role, eligibility criteria and application process.</p>
<p class="MsoNormal"><a title="https://us.list-manage.com/W8CbB2O5npb?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/W8CbB2O5npb?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e">Read reflections from current Ask-JGI team members</a>&nbsp;to hear first-hand what it is like to work on the helpdesk.</p>
<p class="MsoNormal">&nbsp;</p><br><br><b><p>Welcome week!</p></b><br><p>A big welcome to our new cohort of PrOAI students who have settled into the ISL zone and had a busy week of Welcome Week activities. The last activity of the week is the ProAI 25 cohort's summer project presentations followed by a Social board game session.</p><br><br><b><p>BAIS 2026 (Summer School)</p></b><br><p>Thankyou to everyone who attended and helped with the Summer School: particular thanks to CDT students Bezawit, Jack Burnett and Joseph who brought everyone together. If you have any feedback on the event or would like to help organise the next CDT event, please email <a href="mailto:iai-cdt@bristol.ac.uk">iai-cdt@bristol.ac.uk</a></p>
<p>&nbsp;</p>
<p>&nbsp;</p><br><br><b><p><span data-olk-copy-source="MessageBody">Sloane Robinson Building - Current opening hours</span></p></b><br><p>The building opening hours are as follows for ucard holders:</p>
<p>Standard Extended Always</p>
<p>Mon, Tue, Thu, Fri 07:30 - 20:00, &nbsp;07:30 - 22:00 (extended hours)</p>
<p>Wed 07:30 - 22:00, 07:30 - 22:00 (extended hours)</p>
<p>Sat 09:00 - 18:00, 09:00 - 20:00 (extended hours)</p>
<p>Sun 10:00 - 18:00, 10:00 - 20:00 (extended hours)</p>
<p>There are reduced hours for the public.</p>
<p>Extended hours will operate during Assessment and Assessment Preparation weeks</p>
<p>(available on the <a title="https://www.bristol.ac.uk/university/dates/" href="https://www.bristol.ac.uk/university/dates/" data-auth="NotApplicable" data-linkindex="0">https://www.bristol.ac.uk/university/dates/</a>)</p>
<p>Access outside of the standard opening hours is currently unavailable. An out of hours access protocol will be issued soon.</p><br><br><b><p>Careers Service support for PGRs</p></b><br><p>In addition to the <a href="https://www.bristol.ac.uk/careers/">Careers Services,</a> for&nbsp;PGR-specific support,&nbsp; visit <a id="OWA268ddcd6-b1e9-3846-7113-55aab52babe4" class="x_OWAAutoLink" title="Original URL: https://uob.sharepoint.com/teams/grp-pgr-careers/SitePages/The-PGR-Compass.aspx. Click or tap if you trust this link." href="https://uob.sharepoint.com/teams/grp-pgr-careers/SitePages/The-PGR-Compass.aspx" data-auth="NotApplicable" data-linkindex="3">PGR Compass</a> which has been designed to help PGRs navigate their careers and offer relevant support&nbsp; structured around the stage of career thinking.&nbsp;</p><br><br><b><p>Bristol Doctoral College (BDC) - events and workshops</p></b><br><p><span data-olk-copy-source="MessageBody">The BDC has a range of workshops to develop new skills, expand your network, and build confidence. For more info and to book a place, visit:</span></p>
<p><span data-olk-copy-source="MessageBody"><a href="https://www.bristol.ac.uk/doctoral-college/events/">Bristol Doctoral College (BDC) events</a></span></p><br><br><b><p>Around Bristol</p></b><br><div>As part of the celebration to mark the 150th year of the University of Bristol, artist Luke Jerram will be exhibiting his new work <em>Pollenarium</em> at University Square on Saturday 10 October.&nbsp;</div>
<div>&nbsp;</div>
<div>You can also hear Luke Jerram in-conversation with Nick Wray, curator of the Bristol Botanic Garden, for an inspiring insight into pollinators, creativity and the health of our planet.&nbsp;<strong data-olk-copy-source="MailCompose"><br>&nbsp;</strong></div>
<div>The celebration will also welcome renowned public historian, author, presenter and film-maker Professor David Olusoga (Hon LLD 2025) to the University&rsquo;s Clifton Campus, for a rare in-person conversation with Dr Marie-Annick Gournet, Associate Pro Vice-Chancellor (Reparative and Civic Futures).&nbsp;</div>
<div><br>These events are part of a&nbsp;free&nbsp;public&nbsp;programme&nbsp;of events across our Clifton campus and&nbsp;new&nbsp;Temple Quarter Enterprise Campus on Saturday 10 October&nbsp;&ndash;&nbsp;<a title="https://us.list-manage.com/YuQVVT5phA2?e=abc15dde10&amp;c2id=cbd77cd006d7be37a5e8c97a97574719" href="https://us.list-manage.com/YuQVVT5phA2?e=abc15dde10&amp;c2id=cbd77cd006d7be37a5e8c97a97574719" data-auth="NotApplicable" data-linkindex="1">you can see the full programme of events here</a></div><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b><p><span data-olk-copy-source="MessageBody">UK AI Research Symposium</span></p> - 2026-09-25</b><br>