---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 07-08-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p>Around Bristol</p></li><li><p>BAIS Summer School</p></li><li><p>Desk booking in Sloane Robinson Building</p></li><li><p>Communications over the summer</p></li><li><p>Bristol Voices buddy programme&nbsp;</p></li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b><p>Around Bristol</p></b><br><p>BBC Proms - hosted at the Bristol Beacon, 7 - 9 August</p>
<p><a href="https://bristolbeacon.org/whats-on/bbc-proms-2026/">https://bristolbeacon.org/whats-on/bbc-proms-2026/</a></p>
<p>Open air cinema at Ashton Court - August screenings</p>
<p>https://adventurecinema.co.uk/venues/ashton-court/</p><br><br><b><p>BAIS Summer School</p></b><br><p>Don't forget to register for <a href="https://www.bristol.ac.uk/cdt/interactive-ai/events/bais-summer-school-2026/">BAIS Summer School,</a> 8 - 10 September at Engineers' House by the latest of 21 August.</p>
<p>All CDT students (except Foundation Year Pr0AI students) are expected to submit a poster for the event. You will need to bring your poster with you on day 1 of the Summer School.&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p><br><br><b><p>Desk booking in Sloane Robinson Building</p></b><br><p>Hubstar is the new system for booking spaces at the Sloane Robinson building.</p>
<p>User guides can be found at: <a href="https://www.bristol.ac.uk/campus-division/workspace-reservations/">https://www.bristol.ac.uk/campus-division/workspace-reservations/</a> - this includes a handy quick start guide.</p>
<p>When booking a desk in the Intelligent System lab (ISL) zone on level 3, please note that desks <strong><span class="NormalTextRun SCXW142815386 BCX8">3.710-00</span><span class="NormalTextRun SCXW142815386 BCX8">1 to </span><span class="NormalTextRun SCXW142815386 BCX8">3.710-0</span></strong><span class="NormalTextRun SCXW142815386 BCX8"><strong>12</strong> are reserved for new PrO-AI students but any of the other desks in the zone are available to book.</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p><br><br><b><p>Communications over the summer</p></b><br><p>Please note that the 'Friday newsletter' is taking a break over August and will resume again in September. If you do have any communications that you would like to be sent out please continue to send to iai-cdt@bristol.ac.uk.</p><br><br><b><p>Bristol Voices buddy programme&nbsp;</p></b><br><div class="x_elementToProof">Application deadline Tuesday 1 September</div>
<div class="x_elementToProof">&nbsp;</div>
<div class="x_elementToProof">Starting life in a new city can be daunting. Bristol Voices links new international postgraduate students with a local alumni to help you make the most of your Bristol experience.</div>
<div class="x_elementToProof">&nbsp;</div>
<div>Join for top tips on the city, advice on life in the UK and to share your experiences with someone from the University alumni community.</div>
<div class="x_elementToProof">&nbsp;</div>
<div class="x_elementToProof">Find out more and apply:&nbsp;<a title="https://forms.office.com/Pages/ResponsePage.aspx?id=MH_ksn3NTkql2rGM8aQVG-8C5Dd2QJ1Co8Er0_B832NUQlU3U0xCMkZGQjMxUkNIVjJDVDU5TUhKVyQlQCN0PWcu" href="https://forms.office.com/Pages/ResponsePage.aspx?id=MH_ksn3NTkql2rGM8aQVG-8C5Dd2QJ1Co8Er0_B832NUQlU3U0xCMkZGQjMxUkNIVjJDVDU5TUhKVyQlQCN0PWcu" data-auth="NotApplicable" data-linkindex="3">https://forms.office.com/Pages/ResponsePage.aspx?id=MH_ksn3NTkql2rGM8aQVG-8C5Dd2QJ1Co8Er0_B832NUQlU3U0xCMkZGQjMxUkNIVjJDVDU5TUhKVyQlQCN0PWcu</a></div><br><br><h2>Forthcoming Calendar of Events</h2><br><br>