---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 20-03-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p><span style="color: rgb(196, 89, 17);"><strong><span class="TextRun SCXW60476628 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW60476628 BCX8">CDT&nbsp;</span><span class="NormalTextRun SCXW60476628 BCX8">AI Symposium &ndash; Foundation and Applications of Trustworthy AI</span></span><span class="EOP SCXW60476628 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></strong></span></p></li><li><p><span style="color: rgb(191, 143, 0);"><strong>Internal call for Google PhD Fellowship applications now open</strong></span></p></li><li><p><span style="color: rgb(168, 93, 156);"><strong><span class="TextRun SCXW120752868 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW120752868 BCX8">Bristol Doctoral College (</span><span class="NormalTextRun SCXW120752868 BCX8">B</span><span class="NormalTextRun SCXW120752868 BCX8">DC</span><span class="NormalTextRun SCXW120752868 BCX8">)</span><span class="NormalTextRun SCXW120752868 BCX8">&nbsp;</span><span class="NormalTextRun SCXW120752868 BCX8">Events and Opportunities</span></span><span class="EOP Selected SCXW120752868 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:1080,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></strong></span></p></li><li><p><span style="color: rgb(70, 156, 146);"><strong>Global Lounge - Spring vacation events (19 March to 10 April)</strong></span></p></li><li><p><span style="color: rgb(62, 163, 184);"><strong>Statistics Seminar: Carl Henrik Ek</strong></span></p></li><li><p><span style="color: rgb(191, 143, 0);"><strong>Around Bristol</strong></span></p></li><li><p><span style="color: rgb(0, 112, 192);"><strong><span class="TextRun SCXW144094288 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW144094288 BCX8" data-ccp-parastyle="List Bullet">Message from the Director</span></span><span class="EOP Selected SCXW144094288 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:360,&quot;335559740&quot;:240,&quot;335559991&quot;:360}">&nbsp;</span></strong></span></p></li></ul><p><p>Welcome to this week's issue of the newsletter. <span class="TextRun SCXW88431496 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW88431496 BCX8">If there is any news, celebration, or event that you would like to share with your colleagues, please email:</span></span><span class="EOP SCXW88431496 BCX8" data-ccp-props="{}">&nbsp;</span></p>
<div class="OutlineElement Ltr SCXW88431496 BCX8">
<p class="Paragraph SCXW88431496 BCX8"><a class="Hyperlink SCXW88431496 BCX8" href="mailto:iai-cdt@bristol.ac.uk" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW88431496 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW88431496 BCX8" data-ccp-charstyle="Hyperlink">iai-cdt@bristol.ac.uk</span></span></a><span class="TextRun SCXW88431496 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW88431496 BCX8">&nbsp;</span></span><span class="EOP Selected SCXW88431496 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div></p><br><br><b><p><span style="color: rgb(196, 89, 17);"><strong><span class="TextRun SCXW60476628 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW60476628 BCX8">CDT&nbsp;</span><span class="NormalTextRun SCXW60476628 BCX8">AI Symposium &ndash; Foundation and Applications of Trustworthy AI</span></span><span class="EOP SCXW60476628 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></strong></span></p></b><br><div class="OutlineElement Ltr SCXW170279472 BCX8">
<p class="Paragraph SCXW170279472 BCX8"><strong><span class="TextRun SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW170279472 BCX8"><span class="TextRun SCXW241772658 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW241772658 BCX8">Date:&nbsp;</span></span></span></span></strong><span class="TextRun SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW170279472 BCX8"><span class="TextRun SCXW241772658 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW241772658 BCX8">27 March</span><span class="NormalTextRun SCXW241772658 BCX8">, 9:30 &ndash; 16:00</span></span></span></span><strong><span class="TextRun SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW170279472 BCX8"><span class="EOP SCXW241772658 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></span></span></strong></p>
<p class="Paragraph SCXW170279472 BCX8"><strong><span class="TextRun SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW170279472 BCX8">Location</span></span></strong><span class="TextRun SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW170279472 BCX8">: MVB 1.11A</span><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;and Lower Atrium</span></span> </p>
<p class="Paragraph SCXW170279472 BCX8"><span class="TextRun SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">This symposium aims to advance understanding of Trustworthy AI by connecting foundational methods and emerging applications, while fostering discussion on how rapid advances in AI are reshaping scientific practice itself. </span></span><span class="TextRun SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">More information including the&nbsp;</span><span class="NormalTextRun SpellingErrorV2Themed SCXW170279472 BCX8">programme</span><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;can be found on the&nbsp;</span></span><a class="Hyperlink SCXW170279472 BCX8" href="https://sites.google.com/view/bristolaisymposium/home" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8" data-ccp-charstyle="Hyperlink">AI Symposium website here.</span></span></a><span class="TextRun SCXW170279472 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;</span></span><span class="EOP SCXW170279472 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW170279472 BCX8">
<p class="Paragraph SCXW170279472 BCX8"><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">Please also&nbsp;</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW170279472 BCX8">remember </span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW170279472 BCX8">to</span><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;complete the&nbsp;</span></span><a class="Hyperlink SCXW170279472 BCX8" href="https://forms.office.com/e/zhfQU7s6Dh" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8" data-ccp-charstyle="Hyperlink">poster form</span></span></a><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;</span><span class="NormalTextRun SCXW170279472 BCX8">to let us know about your&nbsp;</span></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">poster</span></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;submission for the Symposium (this&nbsp;</span><span class="NormalTextRun SCXW170279472 BCX8">doesn't</span><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;include the Foundation Year Pro-AI cohort):</span> </span><a class="Hyperlink SCXW170279472 BCX8" href="https://forms.office.com/e/zhfQU7s6Dh" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8" data-ccp-charstyle="Hyperlink">https://forms.office.com/e/zhfQU7s6Dh</span></span></a><span class="EOP SCXW170279472 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW170279472 BCX8">
<p class="Paragraph SCXW170279472 BCX8"><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">Posters</span><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;</span><span class="NormalTextRun SCXW170279472 BCX8">must be in the following format:</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW170279472 BCX8"><span class="SCXW170279472 BCX8">&nbsp;</span><br class="SCXW170279472 BCX8"></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">        &bull; A1, portrait</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW170279472 BCX8"><span class="SCXW170279472 BCX8">&nbsp;</span><br class="SCXW170279472 BCX8"></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">        &bull; include a title</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW170279472 BCX8"><span class="SCXW170279472 BCX8">&nbsp;</span><br class="SCXW170279472 BCX8"></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">        &bull; your name and email address</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW170279472 BCX8"><span class="SCXW170279472 BCX8">&nbsp;</span><br class="SCXW170279472 BCX8"></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">        &bull; names of supervisors</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW170279472 BCX8"><span class="SCXW170279472 BCX8">&nbsp;</span><br class="SCXW170279472 BCX8"></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">        &bull; the UOB, UKRI, and IAI/Pro-AI logos</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW170279472 BCX8"><span class="SCXW170279472 BCX8">&nbsp;</span><br class="SCXW170279472 BCX8"></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">        &bull; acknowledge any sponsors</span></span> </p>
<p class="Paragraph SCXW170279472 BCX8"><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">Final posters</span><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;</span><span class="NormalTextRun SCXW170279472 BCX8">submission (PDF format please) deadline is&nbsp;</span></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">Friday</span></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;</span></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">20 March</span></span><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">, 10am to&nbsp;</span></span><a class="Hyperlink SCXW170279472 BCX8" href="mailto:iai-cdt@bristol.ac.uk" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8" data-ccp-charstyle="Hyperlink">iai-cdt@bristol.ac.uk</span></span></a><span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">&nbsp;so that we can send them to the Printers at 10am.</span></span> <span class="TextRun SCXW170279472 BCX8" lang="EN-GB" xml:lang="EN-GB" data-contrast="none"><span class="NormalTextRun SCXW170279472 BCX8">Please let us know on the form in the comments section if you are unable to meet the deadline and will make your own arrangements with Print Services</span><span class="NormalTextRun SCXW170279472 BCX8">.</span></span><span class="EOP SCXW170279472 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;</span></p>
</div><br><br><b><p><span style="color: rgb(191, 143, 0);"><strong>Internal call for Google PhD Fellowship applications now open</strong></span></p></b><br><div class="x_elementToProof"><span data-olk-copy-source="MessageBody">The 2026&nbsp;call for&nbsp;</span><u><a id="OWAe70fe8b6-6645-9ef3-b7a4-4e0fb1ee3f80" class="x_Hyperlink x_SCXW245380485 x_BCX8 x_OWAAutoLink" title="https://research.google/outreach/phd-fellowship/" href="https://research.google/outreach/phd-fellowship/" target="_blank" rel="noreferrer noopener" data-auth="NotApplicable" data-linkindex="0">Google PhD Fellowships</a></u>&nbsp;is now&nbsp;open!&nbsp;Bristol can&nbsp;nominate up to&nbsp;three&nbsp;students for this prestigious award, and&nbsp;we invite&nbsp;short applications&nbsp;for&nbsp;internal review&nbsp;<strong><u>by Friday 27th March 2026, 17:00, </u></strong><u><a id="OWAf9acb74b-2e8c-ed32-3e95-6e5017ba0d92" class="x_Hyperlink x_SCXW245380485 x_BCX8 x_OWAAutoLink" title="https://forms.office.com/e/tfLrn7wQGN" href="https://forms.office.com/e/tfLrn7wQGN" target="_blank" rel="noreferrer noopener" data-auth="NotApplicable" data-linkindex="1">through this Microsoft form</a></u>. The three strongest eligible candidates will then be invited to complete a full proposal in time for the final Google deadline on 30th April.</div>
<div class="x_elementToProof">
<div class="x_elementToProof"><strong data-olk-copy-source="MessageBody">How to&nbsp;submit&nbsp;an internal&nbsp;application</strong>&nbsp;</div>
<div class="x_elementToProof">Please complete this&nbsp;short form:&nbsp;<u><a id="OWA2fba8ae7-1cd0-c5f0-4c81-061422d44fc0" class="x_Hyperlink x_SCXW245380485 x_BCX8 x_OWAAutoLink" title="https://forms.office.com/e/tfLrn7wQGN" href="https://forms.office.com/e/tfLrn7wQGN" target="_blank" rel="noreferrer noopener" data-auth="NotApplicable" data-linkindex="5">Google PhD Fellowships 2026 - Internal Call</a></u>&nbsp;</div>
<div class="x_elementToProof">Where&nbsp;possible, proposals should be&nbsp;submitted&nbsp;by candidates&rsquo; supervisors. Proposals&nbsp;submitted&nbsp;directly by students currently enrolled at Bristol will, however, also be accepted.&nbsp;</div>
<div class="x_elementToProof">Responses should include:&nbsp;</div>
<ol start="1">
<li>
<div class="x_elementToProof" role="presentation"><strong>Student details</strong>,&nbsp;<em>including&nbsp;a&nbsp;short narrative description of research experience&nbsp;and&nbsp;track record,&nbsp;as well&nbsp;as details of supervisor,&nbsp;faculty&nbsp;and school;</em>&nbsp;</div>
</li>
<li>
<div class="x_elementToProof" role="presentation"><strong>Project summary&nbsp;(maximum 500 words)</strong>&nbsp;to be uploaded.&nbsp;<em>The project summary should be&nbsp;accessible for those who&nbsp;are not specialists in specific field of candidate&rsquo;s research. If&nbsp;a&nbsp;candidate is successful in receiving&nbsp;a&nbsp;nomination, they will be invited to make the proposal in greater technical detail&nbsp;at the formal&nbsp;application stage;</em>&nbsp;</div>
</li>
<li>
<div class="x_elementToProof" role="presentation"><strong>Candidate CV&nbsp;</strong>to be uploaded.&nbsp;</div>
</li>
</ol>
<div class="x_elementToProof">Please&nbsp;don&rsquo;t&nbsp;hesitate to get in touch&nbsp;at&nbsp;<u><a id="OWA3fdc1f63-5478-60c1-cd43-451cfcdf5fb8" class="x_Hyperlink x_SCXW245380485 x_BCX8 x_OWAAutoLink" title="mailto:doctoral-college@bristol.ac.uk" href="mailto:doctoral-college@bristol.ac.uk" data-linkindex="6">doctoral-college@bristol.ac.uk</a></u> if you have&nbsp;any further questions&nbsp;about this opportunity.&nbsp;</div>
</div><br><br><b><p><span style="color: rgb(168, 93, 156);"><strong><span class="TextRun SCXW120752868 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW120752868 BCX8">Bristol Doctoral College (</span><span class="NormalTextRun SCXW120752868 BCX8">B</span><span class="NormalTextRun SCXW120752868 BCX8">DC</span><span class="NormalTextRun SCXW120752868 BCX8">)</span><span class="NormalTextRun SCXW120752868 BCX8">&nbsp;</span><span class="NormalTextRun SCXW120752868 BCX8">Events and Opportunities</span></span><span class="EOP Selected SCXW120752868 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:1080,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></strong></span></p></b><br><div class="SCXW33361215 BCX8">
<div class="ListContainerWrapper SCXW33361215 BCX8">
<p class="Paragraph SCXW33361215 BCX8"><strong><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">1. 5 Weeks of Wellbeing (upcoming events for PGR students) </span></span><span class="EOP Selected SCXW33361215 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></strong></p>
</div>
<div class="OutlineElement Ltr SCXW33361215 BCX8">
<p class="Paragraph SCXW33361215 BCX8"><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">This March,&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">we&rsquo;re</span><span class="NormalTextRun SCXW33361215 BCX8">&nbsp;inviting PGR students to slow down, breathe out, and make space for the parts of life that&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">don&rsquo;t</span><span class="NormalTextRun SCXW33361215 BCX8">&nbsp;revolve around research. Over five themed weeks,&nbsp;</span></span><a class="Hyperlink SCXW33361215 BCX8" href="https://www.bristol.ac.uk/doctoral-college/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8" data-ccp-charstyle="Hyperlink">Bristol Doctoral College</span></span></a><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">&nbsp;will be sharing activities designed to boost your wellbeing, spark joy, help you connect with the PGR community, and reconnect with yourself.</span></span> <span class="EOP Selected SCXW33361215 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335557856&quot;:16777215,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW33361215 BCX8">
<ul class="BulletListStyle1 SCXW33361215 BCX8" role="list">
<li class="OutlineElement Ltr SCXW33361215 BCX8" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="5" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1"><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">Week 3 (16&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">-</span><span class="NormalTextRun SCXW33361215 BCX8">&nbsp;20 March) Do Something Physical&nbsp;</span></span></li>
</ul>
</div>
<div class="ListContainerWrapper SCXW33361215 BCX8">
<ul class="BulletListStyle1 SCXW33361215 BCX8" role="list">
<li class="OutlineElement Ltr SCXW33361215 BCX8" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="5" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="4" data-aria-level="1">
<p class="Paragraph SCXW33361215 BCX8"><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">Week 4 (23&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">-</span><span class="NormalTextRun SCXW33361215 BCX8">&nbsp;27 March) Learn a New Skill&nbsp;</span></span><span class="EOP Selected SCXW33361215 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335557856&quot;:16777215,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="ListContainerWrapper SCXW33361215 BCX8">
<ul class="BulletListStyle1 SCXW33361215 BCX8" role="list">
<li class="OutlineElement Ltr SCXW33361215 BCX8" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="5" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:720,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="5" data-aria-level="1">
<p class="Paragraph SCXW33361215 BCX8"><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">Week 5 (30 March&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">-</span><span class="NormalTextRun SCXW33361215 BCX8">&nbsp;3 April) Be Mindful&nbsp;</span></span><span class="EOP Selected SCXW33361215 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335557856&quot;:16777215,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW33361215 BCX8">
<p class="Paragraph SCXW33361215 BCX8"><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">Get to know the PGR Clubs, join&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">the&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">lunchtime Wednesday Wellbeing Walks, or sign up for one of our other workshops,&nbsp;</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW33361215 BCX8">think</span><span class="NormalTextRun SCXW33361215 BCX8">&nbsp;zine making, yoga, a mending workshop, a group cycle&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">ride, or even a soothing sound bath. All the events are free to attend and exclusively for postgraduate researchers.&nbsp;</span></span><span class="EOP Selected SCXW33361215 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335557856&quot;:16777215,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
</div>
</div>
<div class="OutlineElement Ltr SCXW33361215 BCX8">
<p class="Paragraph SCXW33361215 BCX8"><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">See all the upcoming opportunities on&nbsp;</span><span class="NormalTextRun SCXW33361215 BCX8">BDC</span><span class="NormalTextRun SCXW33361215 BCX8">&nbsp;</span></span><a class="Hyperlink SCXW33361215 BCX8" href="https://www.bristol.ac.uk/doctoral-college/events/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">events calendar</span></span></a><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">, just&nbsp;</span></span><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">filter the tags to 5 Weeks of Wellbeing</span></span><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">.</span></span><span class="EOP Selected SCXW33361215 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335557856&quot;:16777215,&quot;335559739&quot;:0,&quot;335559740&quot;:257}">&nbsp;</span></p>
<p><strong><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8">2. <span data-olk-copy-source="MessageBody">ND x LGBTQ+ Network Activity-Based Mixer</span></span></span></strong></p>
<p><strong><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8"><span data-olk-copy-source="MessageBody">Date: </span></span></span></strong><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8"><span data-olk-copy-source="MessageBody">31 March, 16:30 - 17:00</span></span></span></p>
<p><strong><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8"><span data-olk-copy-source="MessageBody">Location: </span></span></span></strong><span class="TextRun SCXW33361215 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW33361215 BCX8"><span data-olk-copy-source="MessageBody">PGR Hub</span></span></span></p>
<p class=""><span data-olk-copy-source="MessageBody">Event welcome to any PGR or staff identifying as Neurodivergent or LGBTQ+.</span></p>
<p>The Neurodivergent PGR Network, LGBTQ+ Staff Network, and Trans &amp; Non-binary PGR Networks will be joining for an evening of crafts and mingling. Lego, paper crafts, and colouring sheets will be provided - feel free to bring your own project along, come just to chat, or just to hang out in a friendly, inclusive, and low-pressure environment.</p>
<p class="x_mcePastedContent x_last-child">Please email&nbsp;<a title="mailto:nd-pgr-network@bristol.ac.uk?subject=&amp;body=" href="mailto:nd-pgr-network@bristol.ac.uk?subject=&amp;body=" data-linkindex="34">nd-pgr-network@bristol.ac.uk</a> if you have any questions or would like to register your interest.</p>
</div><br><br><b><p><span style="color: rgb(70, 156, 146);"><strong>Global Lounge - Spring vacation events (19 March to 10 April)</strong></span></p></b><br><p>If you are staying in Bristol over the vacation period, it&rsquo;s a great chance to meet up with others, learn about spring and Easter traditions and enjoy some free chocolate mini eggs! Come along each week to Culture Club, Language Caf&eacute; and Friday Hangouts. Make friends from around the world, learn something new and enjoy our friendly, welcoming community. <span data-olk-copy-source="MessageBody">There will be an event on the last day before closure, Thursday 2 April, and then after the University reopens on Wednesday 8 April.&nbsp;</span></p>
<p>See all of upcoming events on <a href="https://global-lounge.bristol.ac.uk/events/">Global Lounge: Upcoming events</a></p>
<div id="timely-custom-display-section-timely-iframe-container-timely-iframe-embed-0" class="timely-custom-display timely-custom-display-visible"></div><br><br><b><p><span style="color: rgb(62, 163, 184);"><strong>Statistics Seminar: Carl Henrik Ek</strong></span></p></b><br><div class="x_elementToProof"><strong data-olk-copy-source="MessageBody">Time: </strong>13:00 - 14:00</div>
<div class="x_elementToProof"><strong data-olk-copy-source="MessageBody">Location: </strong><span data-olk-copy-source="MessageBody">Fry building 2.04</span></div>
<div class="x_elementToProof"><strong data-olk-copy-source="MessageBody">Title:</strong> Approximate Bayesian Inference of Composite Functions</div>
<div class="x_elementToProof"><strong>Abstract:&nbsp;</strong>Over the last decade machine learning methods built on composite functions have lead to a remarkable increase in predictive power. Building complex structures from compositions of simple mathematical objects have lead to a surprising generalisation of success across many domains. However, in order to use these methods in critical scenarios in a safe manner our models need to be able to quantify their knowledge. The aspiration of Bayesian deep learning is to combine the predictive advantages of deep neural networks with the theoretical justifications of the Bayesian framework in order to provide predictions with quantified and interpretable uncertainty. Success in achieving this promises has been so elusive that it raises the question if there is something inherent in their structure that renders it numb to a Bayesian approach</div>
<div class="x_elementToProof">In this talk I will first highlight the inherent structures in the compositional models that makes Bayesian approximate inference challenging. We will provide a characterization of why Bayesian learning has not succeeded, showing that for deep learning to harvest the benefit of a Bayesian treatment, this structure needs to be reflected in the approximate posterior. We will then discuss how we can use tools from differential geometry to characterise the structures of these parameter spaces to design efficient computational models to circumvent the issues and design tailored approximate inference schemes that removes the pathological behaviour associated with a direct approximate inference.</div><br><br><b><p><span style="color: rgb(191, 143, 0);"><strong>Around Bristol</strong></span></p></b><br><p><strong>Brain Rot (Bristol)</strong></p>
<p><strong>Date:&nbsp;</strong>26 March, 16:30 - 18:00</p>
<p><strong>Location</strong>: Peel Lecture Theater, <span class="ng-star-inserted">Geographical Sciences Building&nbsp;</span><span class="ng-star-inserted">University of Bristol</span></p>
<p><span class="ng-star-inserted">Dr Imogen Blake has agreed to all her lectures being delivered by a photo-real, voice cloned avatar of herself. &nbsp;But on one condition. &nbsp;That she gets to deliver one last lecture IRL&hellip;<br>Kilter Theatre in collaboration with the Universities of Bristol and Bath Cybersecurity Centre for Doctoral Training invite you to a vision of generative AI and the future of universities&hellip; in a lecture like no other. Admission Free.&nbsp;<a href="https://www.ticketsource.co.uk/cdt-cse/brain-rot-bristol/2026-03-26/16:30/t-qmjpdlq">Book now.</a></span></p><br><br><b><p><span style="color: rgb(0, 112, 192);"><strong><span class="TextRun SCXW144094288 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW144094288 BCX8" data-ccp-parastyle="List Bullet">Message from the Director</span></span><span class="EOP Selected SCXW144094288 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:360,&quot;335559740&quot;:240,&quot;335559991&quot;:360}">&nbsp;</span></strong></span></p></b><br><div data-olk-copy-source="MessageBody">If you haven't done your Cyber Security and Data Protection Essentials essential training on Develop, please do so now or suffer the consequences in terms of loss of access to university IT systems -- you have been warned...</div><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b><p><span style="color: rgb(62, 163, 184);"><strong>Statistics Seminar: Carl Henrik Ek</strong></span></p> - 2026-03-20</b><br><b><p><span style="color: rgb(196, 89, 17);"><strong><span class="TextRun SCXW60476628 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW60476628 BCX8">CDT&nbsp;</span><span class="NormalTextRun SCXW60476628 BCX8">AI Symposium &ndash; Foundation and Applications of Trustworthy AI</span></span><span class="EOP SCXW60476628 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></strong></span></p> - 2026-03-27</b><br>