---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 10-07-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p>Around Bristol</p></li><li><p>Annual CDT survey - deadline 18 July</p></li><li><p>Future Frontiers</p></li><li><p>Research Frontiers Podcast</p></li><li><p>Move to Temple Quarter</p></li><li><p>Forthcoming Research Seminar</p></li><li><p>Congratulations!</p></li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b><p>Around Bristol</p></b><br><p><a id="OWAaf4fb83b-c4d0-ab36-98f0-2ab880599a45" title="https://bristolpride.co.uk/pride-day/" href="https://bristolpride.co.uk/pride-day/" data-auth="NotApplicable" data-linkindex="8" data-olk-copy-source="MessageBody">Pride Day</a> - 11 July, The Downs</p>
<p>Bristol Harbour Festival - 17 - 19 July</p>
<p><a href="https://www.bristolharbourfestival.co.uk/">https://www.bristolharbourfestival.co.uk/</a></p>
<p>Cinema Rediscovered Festival - 22 - 26 July, various venues including Watershed, The Cube</p>
<p>70+ events including screenings of newly restored films (incl. 17 UK premieres), rediscoveries and film-on-film rarities plus projection tours, cinema walks, improv workshops, a FREE interactive BFI National Archive exhibition.&nbsp;</p>
<p>https://www.watershed.co.uk/cinema-rediscovered-2026</p>
<p>&nbsp;</p><br><br><b><p>Annual CDT survey - deadline 18 July</p></b><br><p><span data-olk-copy-source="MailCompose">You've still got time to complete the </span><a id="OWAc1faf8cb-4425-6b9a-6124-bd494b2baa24" class="OWAAutoLink" title="https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=MH_ksn3NTkql2rGM8aQVGzPijOSkMMlCp2NRiaR2Bw1URjFTV0lKN05WUlZXNTlTNTlOV0tCMkJBWi4u" href="https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=MH_ksn3NTkql2rGM8aQVGzPijOSkMMlCp2NRiaR2Bw1URjFTV0lKN05WUlZXNTlTNTlOV0tCMkJBWi4u" data-auth="NotApplicable" data-linkindex="0">CDT Annual programme survey for the year 2025-26</a>&nbsp; It should only take about 5 minutes to complete and will be valuable in helping us take stock and plan for the future. Deadline: <strong>18 July</strong></p><br><br><b><p>Future Frontiers</p></b><br><p class="x_mcePastedContent" data-olk-copy-source="MessageBody">Tuesday 21 July, 5:30 to 8:30 pm, Bristol.&nbsp;Free to attend.</p>
<p class="">Join ARIA, 5050 UK and PRIMED for an evening of discussion exploring ambitious technology ideas at the frontier of scientific and technological innovation. Participants will share short talks and debate the challenges and opportunities involved in turning bold concepts into reality.</p>
<p class="x_mcePastedContent x_last-child"><a title="https://us.list-manage.com/dvcDraoDlfu?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/dvcDraoDlfu?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" data-auth="NotApplicable" data-linkindex="23">Find out more</a></p><br><br><b><p>Research Frontiers Podcast</p></b><br><p>Research Frontiers is a podcast series from the University of Bristol that highlights how the University's groundbreaking research informs teaching on the 150+ postgraduate programmes available at Bristol.</p>
<p>To find out more visit:</p>
<p>https://www.bristol.ac.uk/study/research-frontiers/</p><br><br><b><p>Move to Temple Quarter</p></b><br><p>As well as remembering to clear out your locker before the moving date of the 17 August, please also retrieve any of your personal items from the cupboards in the kitchen area in 1CS. The Move Team will then clear out any remaining items shortly before the move date.</p><br><br><b><p>Forthcoming Research Seminar</p></b><br><div data-olk-copy-source="MessageBody">You are invited to attend a research seminar from <a href="https://vivo.brown.edu/display/mbessa">Miguel Bessa,</a> Associate Professor, Brown University on&nbsp; July 17, 12:00, room 1.15, Queen's Building.&nbsp;</div>
<div>&nbsp;</div>
<div><strong>Title: </strong><em><strong>Disentangling uncertainty in AI for Engineering</strong></em></div>
<div><strong>Abstract:</strong></div>
<div>Neural networks are usually trained for deterministic predictions. Methods that do quantify uncertainty conflate two distinct sources: the model's ignorance where data is sparse (epistemic), and the irreducible noise in the data-generating process (aleatoric). Disentangling them is essential &mdash; epistemic uncertainty tells us where to acquire more data; aleatoric uncertainty tells us what variability we must design around. Yet recent benchmarks show that no existing method reliably disentangles the two in practice [Mucs&aacute;nyi et al., 2024]. This talk presents Variance estimation Bayesian Neural Networks (VeBNNs), recently accepted at ICML 2026, which resolve this through a three-step cooperative training strategy: a deterministic mean network, a variance network trained on residuals via a Gamma likelihood, and Bayesian inference with the aleatoric variance held fixed. The method is architecture-agnostic and demonstrated across UCI regression, ResNet-34 image regression under distribution shift, and a new plasticity constitutive model learning problem &mdash; possibly the first open dataset with known ground-truth aleatoric uncertainty. I will close with the design of recycled polypropylene/polyethylene blends, where batch variability spans orders of magnitude in failure strain. Uncertainty-aware inverse optimization with VeBNN yields blends that are most reliable, not most extreme. The next step, which we are pursuing, is principled Bayesian optimization on top of VeBNN. The same principle reaches further: into uncertainty at foundation-model scale, where networks are trained as point estimates of intractable posteriors, and into gating in agentic systems, where calibrated distributions may matter more than confidence scores.</div><br><br><b><p>Congratulations!</p></b><br><div><span data-olk-copy-source="MessageBody">Many <span class="markkpxz1hb82 uM2yb" data-markjs="true">congratulations </span></span><span data-olk-copy-source="MessageBody">&nbsp;to the IAI CDT students who graduated this week:&nbsp; Drs&nbsp;</span></div>
<div>Kevin Kermani Nejad and Tashi Namgyal (2020 cohort) and Ellie Prosser (2021 cohort)</div>
<div>&nbsp;</div><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b><p>Forthcoming Research Seminar</p> - 2026-07-17</b><br><b><p>Future Frontiers</p> - 2026-07-21</b><br>