---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 24-07-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p>Final coffee morning at 1CS - Reminder</p></li><li><p><span data-olk-copy-source="MessageBody">Upcoming focus group for the SPRITE+ AI Development Best Practice Pipeline Tool - volunteers needed</span></p></li><li><p>Internship opportunity (part-time) &ndash; XAI in Insurance Fraud</p></li><li><p>Move to Sloane Robinson building at Temple Quarter - updated info</p></li><li><p>BAIS Summer School</p></li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b><p>Final coffee morning at 1CS - Reminder</p></b><br><p><span data-olk-copy-source="MailCompose">Everyone is warmly invited to a coffee morning in the 1CS Ground floor kitchen on <strong>Thursday&nbsp;30 July</strong>, 11 - 11.30am. This will be the last chance for all to come together in 1CS before the move to Temple Quarter in August. Please join us if you can.</span></p><br><br><b><p><span data-olk-copy-source="MessageBody">Upcoming focus group for the SPRITE+ AI Development Best Practice Pipeline Tool - volunteers needed</span></p></b><br><p>We are developing a software prototype designed to help organisations build AI systems in ways that are ethical, transparent, safe, and compliant with relevant regulation. We are inviting a small group of Bristol PhD students, academics, and technical researchers to test the prototype and, quite deliberately, try to &ldquo;break&rdquo; it by identifying bugs, weaknesses, unclear processes, and unexpected behaviour.&nbsp;</p>
<p>The session will take place as follows:</p>
<div>
<ul type="disc">
<li><strong>Date:</strong> Thursday 17 September</li>
</ul>
</div>
<div>
<ul type="disc">
<li><strong>Time:&nbsp;</strong>11am&ndash;3pm, although we will aim to finish the main activities by around 2pm (lunch provided)</li>
</ul>
</div>
<div>
<ul type="disc">
<li><strong>Location:&nbsp;</strong>G.07, The Workshop Room, Bristol Digital Futures Institute</li>
</ul>
</div>
<p>If interested, please email <span data-olk-copy-source="MessageBody">peter.winter@bristol.ac.uk</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p><br><br><b><p>Internship opportunity (part-time) &ndash; XAI in Insurance Fraud</p></b><br><div><span data-olk-copy-source="MailCompose">We are currently working on a collaboration with Allianz Insurance exploring explainable AI in Insurance Fraud investigation workflows</span></div>
<div>As part of this project we have an opening for a paid part-time intern (about 2 days/week during August and September) to work with us on a research project exploring how to make current explainable AI methods more user-friendly. We are using LLMs to generate explanatory text that fraud handlers a better understanding of a fraud alert model&rsquo;s decision based on SHAP values and contextual information of the model. The intern&rsquo;s job will be to extend existing python XAI libraries to include LLM generated explanations and experiment with different models and datasets. The aim is to find out what types of information will be the most effective and useful to generate explanations and how to best deliver this information within an LLM prompt.</div>
<div>&nbsp;</div>
<div>What will you gain? You will receive insights and hands-on experience of an applied context of XAI methods, LLM prompting and human-computer interaction. You will benefit from mentoring from senior academics and industry partners&rsquo; data science team.</div>
<div>&nbsp;</div>
<div>What will you bring? Skills in Python, explainable AI and/or LLM prompting.</div>
<div>&nbsp;</div>
<div>If interested, please contact: Dr Vanessa Hanscke -&nbsp;<a title="vanessa.hanschke@bristol.ac.uk" href="mailto:vanessa.hanschke@bristol.ac.uk">vanessa.hanschke@bristol.ac.uk</a>, Dr Zahraa Abdallah - <a title="zahraa.abdallah@bristol.ac.uk" href="mailto:zahraa.abdallah@bristol.ac.uk">zahraa.abdallah@bristol.ac.uk</a> or Professor Kenton O&rsquo;Hara &ndash; <a title="kenton.ohara@bristol.ac.uk" href="mailto:kenton.ohara@bristol.ac.uk">kenton.ohara@bristol.ac.uk</a></div><br><br><b><p>Move to Sloane Robinson building at Temple Quarter - updated info</p></b><br><p><span data-olk-copy-source="MailCompose">If you have ordered a crate to move any items to the Sloane Robinson Building, these will arrive (along with labels) in 1CS on Monday 27 July.&nbsp;</span></p>
<p>All your items will need to be emptied from the building on the move date of 17 August so please make sure everything that is moving is boxed up and labelled and anything else is disposed of.</p><br><br><b><p>BAIS Summer School</p></b><br><p><span data-olk-copy-source="MailCompose">Registration will shortly open for BAIS Summer School at Engineers' House, 8 - 10 September.&nbsp; For those students submitting a poster (all except the Pr0AI foundation year) you will have received details including budget code so that you can send your poster to Print Services for printing. <strong>Please note:</strong>&nbsp; You will need to bring your poster with you on Day 1 of the Summer School on the 8 September.</span></p><br><br><h2>Forthcoming Calendar of Events</h2><br><br>