---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 09-10-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p>Conduct Ethical Research and Project Supervision</p></li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b><p>Conduct Ethical Research and Project Supervision</p></b><br><p><strong>13 October 2026, 1:00pm - 2:00pm, <a href="https://teams.microsoft.com/meet/347564524275426?p=8n9h8uizkDu69xDZYv">Online (Microsoft Teams)</a></strong></p>
<p>Join Aisling O'Kane, Andrew Calway and Oussama Metatla, members of the University Research Ethics Committee, for an overview of the ethics approval process and what you need to know when planning and carrying out research.</p>
<p>The session will cover what constitutes ethical research, when and why ethics approval is required, the application process, amendments and the student ethics process. There will also be an opportunity to discuss common issues and challenges, ask questions and seek guidance on specific queries.</p>
<p><span data-olk-copy-source="MessageBody">If you have any topics you would like to see covered in a future How-To Session, or would like to contribute to a session yourself, please let us know by emailing <a href="mailto:cs-staff-enquiries@bristol.ac.uk">cs-staff-enquiries@bristol.ac.uk</a>&nbsp;</span></p><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b><p><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-font-kerning: 0pt; mso-ligatures: none; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB; mso-bidi-language: AR-SA;">UK AI Research Symposium </span></p> - 2026-11-24</b><br>