---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 02-10-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p>Bristol University Press at Bristol's 150th Anniversary Event</p></li><li><p>AI Connect: Research Meets Industry</p></li><li><p>Turing Internship Network - Applications now open!</p></li><li><p>REWIRE Annual Showcase</p></li><li><p>Mandatory Training Reminder&nbsp;</p></li><li><p>BI Innovators Forum</p></li><li><p>Bristol Doctoral College (BDC) Events and Opportunities</p></li><li><p>BDFI Guest Lecture: Inside the Making of Two EU AI Laws</p></li><li><p><strong><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: #0c882a; mso-fareast-language: EN-GB;">AI CDT Lunch and Learn Seminar</span></strong></p></li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b><p>Bristol University Press at Bristol's 150th Anniversary Event</p></b><br><p><strong>2pm&ndash;5pm 10th October,&nbsp;Story Exchange at Temple Quarter Enterprise Campus.</strong></p>
<p>Did you know the University of Bristol has its own academic publisher?</p>
<p><a href="https://bristoluniversitypress.co.uk/">Bristol University Press</a> will be at the University's 150th Anniversary Event on 10 October at Temple Quarter Enterprise Campus.</p>
<p>Visit the stand to learn more about academic publishing, explore BUP's books and journals, and discover resources available to University staff and students. The editorial team will also be hosting a session at the Story Exchange to answer questions about the publishing process.</p>
<p>Have a book idea? Come and talk to the team.</p><br><br><b><p>AI Connect: Research Meets Industry</p></b><br><p class="MsoNormal"><strong>26 - 27 November 2026, Burg Frankenberg, Aachen, Germany</strong></p>
<p class="MsoNormal"><a href="https://cairne.eu/portfolio-items/26-27-11-26-ai-connect-research-meets-industry/">AI Connect: Research Meets Industry</a> will bring together around 50 young AI researchers, company representatives and partners from across the AI ecosystem. Participants will explore real-world challenges presented by Carglass, Unchained Robotics, JUPITER AI Factory (JAIF) and Cognita Reply, and consider how AI research could lead to practical solutions.</p>
<p class="MsoNormal">The programme will include presentations and keynotes, interactive small-group workshops, group pitches and opportunities to meet researchers, companies and ecosystem partners.</p>
<p class="MsoNormal">The event will be held in English and participation is free of charge. Places are limited and participants will be selected from applications received.</p>
<p class="MsoNormal"><strong>Application deadline: 9 October 2026<br></strong><a href="https://docs.google.com/forms/d/e/1FAIpQLSdrrw6fTckDII8UWTZjQd5OsA0553XbmASQTz_fUreYGo0LyA/viewform?usp=dialog">Find out more about the company challenges and apply here.</a></p>
<p class="MsoNormal">For questions about the event or your application, please contact Marie Anastacio at <a href="mailto:anastacio@aim.rwth-aachen.de">anastacio@aim.rwth-aachen.de</a>.</p><br><br><b><p>Turing Internship Network - Applications now open!</p></b><br><p class="isSelectedEnd"><strong>Application deadline: 11:00am (UK time), Tuesday 13 October 2026</strong></p>
<p class="isSelectedEnd">A reminder for those still considering applying for the Turing Internship Network.</p>
<p><a href="https://bit.ly/4xNnGeG">Find out more and apply here.</a></p><br><br><b><p>REWIRE Annual Showcase</p></b><br><p class="isSelectedEnd"><strong>18 November, Sloane Robinson Building</strong></p>
<p>Power Semiconductor Innovation and Knowledge Centre (REWIRE) is hosting its annual showcase at the Sloane Robinson Building on 18 November. The event is open to everyone interested in learning more about REWIRE&rsquo;s cutting-edge technologies and how they are transforming research into real-world impact.<br><br><strong><a href="https://forms.cloud.microsoft/pages/responsepage.aspx?id=MH_ksn3NTkql2rGM8aQVG4nv3FmlyipOmaWfuLI2U9pUMU5EUTROSEhYNVFCVU1HTExWTkFFSVNDTC4u&amp;amp;route=shorturl">Please complete this form to request a place at the REWIRE Showcase</a> by 30 October 2026.&nbsp;</strong></p>
<p><em>A detailed programme and joining information will be shared with confirmed attendees closer to the event.</em></p><br><br><b><p>Mandatory Training Reminder&nbsp;</p></b><br><p class="isSelectedEnd"><strong>Deadline: 1 February 2027</strong></p>
<p class="isSelectedEnd">Start the academic year with the knowledge and skills you need by completing your 2026/27 mandatory training. The modules provide an important refresh on topics including cyber security and data protection, and fire safety, to help keep you safe and supported at work.</p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; background: white; vertical-align: baseline;"><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">To all PGRs, please ensure you complete all your mandatory training on&nbsp;</span><span style="color: black; mso-color-alt: windowtext;"><a title="https://develop.bristol.ac.uk/ilp/pages/external-dashboard.jsf?menuId=1104&amp;locale=en-GB#/?dashboardId=6" href="https://develop.bristol.ac.uk/ilp/pages/external-dashboard.jsf?menuId=1104&amp;locale=en-GB#/?dashboardId=6" target="_blank" rel="noopener"><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: #0563c1; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">Develop</span></a></span><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">&nbsp;by <strong>1 February 2027</strong>. If you do not complete, your access to IT systems will be suspended by the University until it has been undertaken. Please log on to Develop to check what training is outstanding.&nbsp;&nbsp;</span></p><br><br><b><p>BI Innovators Forum</p></b><br><p class="isSelectedEnd"><strong>Thursday 8 October, Bristol Rooms, Sloane Robinson Building</strong></p>
<p class="isSelectedEnd">Are you considering how your research could create impact beyond academia through commercialisation? Join the inaugural BI Innovators Forum and discover how commercialisation can help bring research innovations to the wider world.</p>
<p class="isSelectedEnd">The event will include informal drop-in networking sessions, as well as an Enterprise Roadshow highlighting commercialisation success at the University, with a buffet lunch included.</p>
<p class="isSelectedEnd">Meet members of the Research Commercialisation team and invited guests, connect with fellow researchers interested in commercialisation and entrepreneurship, and hear from University of Bristol academics who have successfully commercialised their research.</p>
<p><a href="https://www.tickettailor.com/events/universityofbristoldrei/2369452">Please book your ticket here</a>.</p><br><br><b><p>Bristol Doctoral College (BDC) Events and Opportunities</p></b><br><p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; background: white; vertical-align: baseline;"><strong><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; mso-color-alt: windowtext; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">1. PGR Board Game Club&nbsp;</span></strong></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><strong><span style="mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: Calibri; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">5 October 2026, 18:00 &ndash; 20:00,</span></strong><strong><span style="font-family: 'Calibri',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;"> </span></strong><strong><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">Senate House (PGR Hub)</span></strong></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">Join the PGR Board Game club for an evening of board game entertainment! Hosted in the PGR Hub&rsquo;s Training Room with food and drink provided, there will be a range of board games available to play, ranging from Werewolf, to Catan, to Forbidden Island!</span></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><span style="color: black; mso-color-alt: windowtext;"><a href="https://www.bristol.ac.uk/doctoral-college/events/#event=78446791;instance=20261005180000?popup=1&amp;lang=en-UK">Book you ticket here.</a></span></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; vertical-align: baseline;"><strong>2. Reading academic literature effectively and efficiently</strong></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><strong><span style="color: black; mso-color-alt: windowtext;">6 October 2026, 10:00-12:00</span></strong><strong><span style="font-family: 'Calibri',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">, </span></strong><strong><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">Senate House (PGR Hub)</span></strong></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><span style="color: black; mso-color-alt: windowtext;">Particularly useful for first-year PhD researchers, but all PGR students are welcome.</span></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><span style="color: black; mso-color-alt: windowtext;">This interactive workshop aims to help you save time by making your reading practices more efficient and effective. You will learn how to manage and process large quantities of literature from your field and read to identify connections and gaps in the field.</span></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><span style="color: black; mso-color-alt: windowtext;">The workshop will be delivered in person at the PGR Hub by expert staff from the Centre for Academic Language and Development (CALD).</span></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><span style="color: black; mso-color-alt: windowtext;"><a href="https://www.bristol.ac.uk/doctoral-college/events/#event=78458988;instance=20261006100000?popup=1&amp;lang=en-UK">Find out more and book</a>.</span></p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; background: white; vertical-align: baseline;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; vertical-align: baseline;"><strong><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">3.&nbsp;&nbsp; PGR Welcome Event</span></strong></p>
<p class="MsoNormal" style="line-height: normal; background: white; vertical-align: baseline; margin: 0cm 0cm 0cm 14.2pt;"><strong><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">7 October 2026, 14:30 - 16:30, Wills Memorial Building (Great Hall)</span></strong></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0cm 14.2pt;"><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">This event is a chance to meet and celebrate the start of your research degree with fellow postgraduate researchers, and to find out about the opportunities available to you throughout your time at Bristol.</span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0cm 14.2pt;"><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">The programme includes a welcome performance by the Chinese Lion Dancing Society, a presentation from the 2026 Three Minute Thesis winner, an opportunity to explore your PGR community, refreshments, and a support services fair featuring University teams.</span></p>
<p class="MsoNormal" style="margin: 0cm 0cm 0cm 14.2pt;"><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;"><a href="https://www.bristol.ac.uk/doctoral-college/events/#event=78456850;instance=20261007143000?popup=1&amp;lang=en-UK">Find out more and book.</a></span></p><br><br><b><p>BDFI Guest Lecture: Inside the Making of Two EU AI Laws</p></b><br><p class="isSelectedEnd">Monday 5 October, 3:30 - 4:30pm, G.07, The Sheds, 65 Avon St, BS2 0PZ</p>
<p class="isSelectedEnd">BDFI is pleased to welcome <a href="https://people.wgtn.ac.nz/ali.knott">Professor Ali Knott</a> from Victoria University of Wellington for a guest lecture exploring the development of two EU laws regulating AI: the AI Act and the Digital Services Act (DSA).</p>
<p class="isSelectedEnd">Professor Knott will discuss his involvement with the Global Partnership on AI in developing policy around AI-generated content and research access to data held by large technology platforms. The talk will explore the challenges of making AI-generated content detectable and the mechanisms that allow researchers to access private platform data to study systemic risks.</p>
<p class="isSelectedEnd">The talk will be followed by refreshments and informal networking.</p>
<p><a href="https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=MH_ksn3NTkql2rGM8aQVG4R9t3DJOPBPn61L4_5cU5hUQllFSjNIMVNLOFVGVlhHN1dDOFI3SzhLSC4u">Please RSVP if you would like to attend.</a></p><br><br><b><p><strong><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: #0c882a; mso-fareast-language: EN-GB;">AI CDT Lunch and Learn Seminar</span></strong></p></b><br><p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; background: white; vertical-align: baseline;"><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; background: white; mso-fareast-language: EN-GB;">Please save the date for our next CDT AI Lunch and Learn Seminar as follows:</span></p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: 14.4pt; background: white; vertical-align: baseline;"><strong><span style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB;">Date</span></strong><span style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB;">: Wednesday 7 October</span></p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: 14.4pt; background: white; vertical-align: baseline;"><strong><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-fareast-language: EN-GB;">Location: </span></strong><span style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB;">Room 3.305, Sloane Robinson Building</span></p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: 14.4pt; background: white; vertical-align: baseline;"><strong><span style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB;">Time</span></strong><span style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB;">: 1:30 - 3pm</span></p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; background: white; vertical-align: baseline;"><strong><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; background: white; mso-fareast-language: EN-GB;">Speaker:</span></strong><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; background: white; mso-fareast-language: EN-GB;"> <a href="https://sheffield.ac.uk/cs/people/research-staff/joe-stacey">Dr Joe Stacey</a> (University of Sheffield)</span></p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; background: white; vertical-align: baseline;"><strong><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; background: white; mso-fareast-language: EN-GB;">Talk Title:</span></strong><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; background: white; mso-fareast-language: EN-GB;"> How to improve the reliability of NLP models in OOD settings.</span></p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: normal; background: white; vertical-align: baseline;"><strong><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: #763e9b; mso-fareast-language: EN-GB;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 0cm; line-height: 14.4pt; background: white; vertical-align: baseline;"><span style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB;">We will have a light lunch </span><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-fareast-language: EN-GB;">and the chance to network with colleagues </span><span style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB;">in the social area, <strong>room 3.710 from 1:30 - 2pm</strong> followed by the talk in <strong>room 3.305 from 2pm - 3pm</strong>. </span><span lang="EN-US" style="font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-fareast-language: EN-GB;">Please join us if you can.</span></p><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b><p><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-font-kerning: 0pt; mso-ligatures: none; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB; mso-bidi-language: AR-SA;">UK AI Research Symposium </span></p> - 2026-11-24</b><br>