---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 28-09-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p><span class="x_normaltextrun"><span class="marknb2hnbw1v" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" data-ogsbtc="" data-ogsbrc="" data-ogsbbc="" data-ogsblc="">Data</span> <span class="mark1hf406tyo" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" data-ogsbtc="" data-ogsbrc="" data-ogsbbc="" data-ogsblc="">Ethics</span> Club</span></p></li><li><p>JGI Training Sessions</p></li><li><p>University Research Institutes reception</p></li><li><p>University of Tokyo/RIKEN AIP events</p></li><li><p>Apply for Thesis Boot Camp</p></li><li><p>Volunteer at a Language Cafe</p></li><li><p>Turing Opportunities</p></li><li><p>Research Capability Hub (RCH) Connect 2026</p></li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b><p><span class="x_normaltextrun"><span class="marknb2hnbw1v" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" data-ogsbtc="" data-ogsbrc="" data-ogsbbc="" data-ogsblc="">Data</span> <span class="mark1hf406tyo" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" data-ogsbtc="" data-ogsbrc="" data-ogsbbc="" data-ogsblc="">Ethics</span> Club</span></p></b><br><p>28 October 2026, online (Zoom), 1 - 2pm</p>
<p>The next meeting of the Data Ethics Club will take place on 28 October. There is no need to register, just pop in!</p>
<p>For more information about the club and upcoming discussions, see&nbsp;<a title="https://dataethicsclub.com/join_in/join_in.html" href="https://dataethicsclub.com/join_in/join_in.html" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" data-linkindex="0"><span class="x_normaltextrun"><span class="marknb2hnbw1v" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" data-ogsbtc="" data-ogsbrc="" data-ogsbbc="" data-ogsblc="">Data</span> <span class="mark1hf406tyo" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" data-ogsbtc="" data-ogsbrc="" data-ogsbbc="" data-ogsblc="">Ethics</span> Club.</span></a><span class="x_eop">&nbsp;</span></p><br><br><b><p>JGI Training Sessions</p></b><br><div class="x_elementToProof">
<p class="x_elementToProof"><span data-olk-copy-source="MessageBody">The </span><a id="OWAe0d317cd-110a-e1d7-94b8-e58303296d0b" class="x_Hyperlink x_SCXW3469941 x_BCX8 x_OWAAutoLink" title="https://www.bristol.ac.uk/golding/" href="https://www.bristol.ac.uk/golding/" target="_blank" rel="noreferrer noopener" data-auth="NotApplicable" data-linkindex="9">Jean Golding Institute</a><u> </u>(JGI) delivers online training in data science and research software engineering which is available to all University of Bristol staff and students. Registration is open and a full list of courses can be found on the<u> </u><a id="OWA130f5117-e9cc-0f8f-97ed-b643a7efb4fb" class="x_Hyperlink x_SCXW3469941 x_BCX8 x_OWAAutoLink" title="https://bristol-training.github.io/upcoming.html" href="https://bristol-training.github.io/upcoming.html" target="_blank" rel="noreferrer noopener" data-auth="NotApplicable" data-linkindex="10">JGI training website</a><u>.</u> These include sessions on Python, R, an Introduction to AI, and Best Practices in Software Engineering.&nbsp;&nbsp;</p>
</div>
<div class="x_elementToProof">
<p class="x_elementToProof"><a id="OWA88f84753-7a41-f42e-3350-afdb5ecd0aa4" class="x_Hyperlink x_SCXW3469941 x_BCX8 x_OWAAutoLink" title="https://bristol-training.github.io/upcoming.html" href="https://bristol-training.github.io/upcoming.html" target="_blank" rel="noreferrer noopener" data-auth="NotApplicable" data-linkindex="11">See the JGI Training Session schedule and book your place here.</a>&nbsp;</p>
</div><br><br><b><p>University Research Institutes reception</p></b><br><p dir="auto" data-start="46" data-end="92"><strong>Wednesday 14 October, 2:00 - 4:30pm, Arts Complex</strong></p>
<p dir="auto" data-start="94" data-end="449">As part of the University&rsquo;s 150th anniversary celebrations, you are welcome to join the University of Bristol&rsquo;s University Research Institutes (URIs) for a special networking and catch-up event, with the <a class="link-596" title="https://www.bristol.ac.uk/brigstow/" href="https://www.bristol.ac.uk/brigstow/" target="_blank" rel="nofollow noopener noreferrer">Brigstow Institute</a>; <a class="link-596" title="https://www.bristol.ac.uk/cabot/" href="https://www.bristol.ac.uk/cabot/" target="_blank" rel="nofollow noopener noreferrer">Cabot Institute for the Environment</a>; <a class="link-596" title="https://www.bristol.ac.uk/blackwell/" href="https://www.bristol.ac.uk/blackwell/" target="_blank" rel="nofollow noopener noreferrer">Elizabeth Blackwell Institute for Health Research</a>; <a class="link-596" title="https://www.bristol.ac.uk/golding/" href="https://www.bristol.ac.uk/golding/" target="_blank" rel="nofollow noopener noreferrer">Jean Golding Institute for Data and AI</a>.</p>
<p dir="auto" data-start="451" data-end="663">Hear how the URIs will be working together over the next three years on big global challenges, and how you can join interdisciplinary research networks, access funding and training opportunities and get involved.</p>
<p dir="auto" data-start="665" data-end="707" data-is-last-node="" data-is-only-node=""><a class="link-596" title="https://forms.cloud.microsoft/e/FmFu61330W" href="https://forms.cloud.microsoft/e/FmFu61330W" target="_blank" rel="nofollow noopener noreferrer">Find out more and register for this event</a>!</p><br><br><b><p>University of Tokyo/RIKEN AIP events</p></b><br><div>Thank you to everyone who joined us for the University of Tokyo/RIKEN AIP Visiting Speaker Event and the joint UoB/RIKEN AIP Workshop this week. We hope you enjoyed the inspiring talks, engaging discussions, and opportunities to connect with colleagues and peers.</div><br><br><b><p>Apply for Thesis Boot Camp</p></b><br><p><strong>Applications close on Thursday 22 October, 11:45pm</strong></p>
<p>Staring at a blinking cursor? Wrestling with that elusive first draft? Thesis Boot Camp might be exactly what you need. This intensive three-day writing retreat (Friday 20 to Sunday 22 November) is designed to help late-stage PGRs break through writer's block and make real progress on their thesis. &nbsp;&nbsp;</p>
<p>Think of it as a focused sprint to get your ideas flowing and words on the page &ndash; with expert support and fellow PGRs cheering you on. &nbsp;&nbsp;</p>
<p>A three-day intensive writing retreat for final-stage PGRs. Overcome writer&rsquo;s block, benefit from dedicated writing time, and make significant progress on your thesis in a supportive environment.</p>
<p><a title="https://us.list-manage.com/1Qds1qntWa6?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/1Qds1qntWa6?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" data-linkindex="10" data-olk-copy-source="MessageBody">Find out more and book</a></p><br><br><b><p>Volunteer at a Language Cafe</p></b><br><p class="isSelectedEnd">Application deadline: <strong>Friday 25 September</strong></p>
<div>Love languages and meeting new people? Volunteer at the Global Lounge&rsquo;s weekly Language Caf&eacute; and connect with students from across the globe. All languages are welcome!&nbsp;<br><a title="https://us.list-manage.com/VXAxGHFS56I?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" href="https://us.list-manage.com/VXAxGHFS56I?e=f73c8a8ff3&amp;c2id=5481753dd6a28b86cbbebc932f88678e" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" data-linkindex="13" data-olk-copy-source="MessageBody">Find out more and apply here</a></div><br><br><b><p>Turing Opportunities</p></b><br><p class="MsoNormal"><strong>&nbsp;</strong></p>
<p class="MsoNormal" style="margin-bottom: 0cm;"><strong>1. <a href="https://bit.ly/4xNnGeG">Turing Internship Network</a> - </strong><strong><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: #242424; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">Applications now open!</span></strong><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: #242424; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom: 0cm;"><span style="mso-ascii-font-family: Aptos; mso-fareast-font-family: 'Times New Roman'; mso-hansi-font-family: Aptos; mso-bidi-font-family: 'Segoe UI'; color: black; border: none windowtext 1.0pt; mso-border-alt: none windowtext 0cm; padding: 0cm; mso-font-kerning: 0pt; mso-ligatures: none; mso-fareast-language: EN-GB;">Deadline to apply: </span><strong>11:00 am (UK time), Tuesday 13 October 2026.</strong></p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">Looking to apply your research skills beyond academia?</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">The Turing Internship Network (TIN) is offering 11 paid internship opportunities with the Alan Turing Institute (6 positions) and the UK Ministry of Justice (5 positions).</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">These exciting 3 -12 month paid internships provide the chance to work on real-world challenges across the justice, sustainability and defence sectors, and gain new skills in a business setting.</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;"><a href="https://bit.ly/4xNnGeG">Find out more and apply here</a></p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;"><strong>2. Turing Institute Funded AI Opportunity for Government Challenges</strong></p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">The Alan Turing Institute is inviting challenge proposals for a <a title="http://www.turing.ac.uk/DSG" href="http://www.turing.ac.uk/DSG" target="_blank" rel="noopener">Data Study Group (DSG)</a> taking place in March 2027 as part of the Open Source AI Fellowship Programme.</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">A DSG is a fully funded five-day research sprint that brings together multidisciplinary AI researchers to tackle real-world problems, generate insights, and produce openly licensed outputs.</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">The Institute is seeking data-rich challenges that support government priorities and could benefit from AI and data science approaches.</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;">If you have a challenge that may be suitable, please review the opportunity details and submit a challenge proposal to <strong><a href="datastudygroup@turing.ac.uk">datastudygroup@turing.ac.uk</a></strong> by <strong>30 September 2026</strong>.</p>
<p class="MsoNormal" style="margin-bottom: 0cm;"><strong><a href="https://www.turing.ac.uk/collaborate-turing/data-study-groups/get-involved-challenge-owner">Find out more about the Data Study Group programme and submit a proposal</a>.</strong></p>
<p class="MsoNormal" style="margin-bottom: 0cm;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0cm;"><em>This opportunity would be covered by the Open Source AI Fellowship grant, funded by Meta.</em></p>
<p class="MsoNormal">&nbsp;</p><br><br><b><p>Research Capability Hub (RCH) Connect 2026</p></b><br><p><strong>21 October 2026, 9:30am to 4:00pm</strong>| Swansea University and Online</p>
<div>
<p>Registration is now open for RCH Connect 2026, the first annual event hosted by the <a href="https://rch.ac.uk">Research Capability Hub (RCH)</a>. Bringing together social science researchers, training providers and organisations from across the UK and beyond.</p>
<p>This event will explore the future of social science research training and capability, with interactive sessions, discussions, networking and opportunities to help shape the development of the Hub. It may be of particular interest to those looking to engage with social science research, broaden interdisciplinary perspectives, or develop collaborative projects across disciplines.</p>
<p>The event will be held at Swansea University, with an online option also available.</p>
</div>
<p><a href="https://rch.ac.uk/en/content/registration-is-now-open-for-the-rch-connect-event-2026">Find out more and register for online or in-person attendance.</a></p><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b><p><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Aptos',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-family: 'Times New Roman'; color: black; mso-font-kerning: 0pt; mso-ligatures: none; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB; mso-bidi-language: AR-SA;">UK AI Research Symposium </span></p> - 2026-11-24</b><br>