---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 26-03-2026

---
<h2>CDT Weekly Newsletter</h2><br><ul><li><p><span style="color: rgb(0, 112, 192);"><strong><span class="TextRun SCXW150979733 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW150979733 BCX8" data-ccp-parastyle="List Bullet">Message from the Director</span></span><span class="EOP Selected SCXW150979733 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:360,&quot;335559740&quot;:240,&quot;335559991&quot;:360}">&nbsp;</span></strong></span></p></li><li><p><span style="color: rgb(191, 143, 0);"><strong><span class="TextRun SCXW157421059 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW157421059 BCX8">Internal call for Google PhD Fellowship applications now open</span></span></strong></span></p></li><li><p><span style="color: rgb(168, 93, 156);"><strong><span class="TextRun SCXW157830351 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW157830351 BCX8">Bristol Doctoral College (BDC) Events and Opportunities&nbsp;</span></span><span class="EOP Selected SCXW157830351 BCX8" data-ccp-props="{}">&nbsp;</span></strong></span></p></li><li><p class="x_elementToProof"><span style="color: rgb(70, 156, 146);"><strong><span class="markbxtidyohu" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" data-olk-copy-source="MessageBody">Global</span>&nbsp;<span class="markkjy8wz63w" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="">Lounge</span>&nbsp;- Spring vacation events (19 March to 10 April)</strong></span></p></li><li><p><span style="color: rgb(230, 126, 35);"><strong>University of Bristol</strong><strong> Innovation </strong><strong>Showcase 2026</strong></span></p></li><li><p><span style="color: rgb(191, 143, 0);"><strong>Around Bristol</strong></span></p></li><li><p><span style="color: rgb(227, 122, 203);"><strong>British Summer Time</strong></span></p></li></ul><p><p>Welcome to this week's issue of the newsletter. <span data-olk-copy-source="MessageBody">If there is any news, celebration, or event that you would like to share with your colleagues, please email:</span></p>
<p class="x_elementToProof"><a id="OWAb6a68203-8527-4e50-5e63-c1471d81d64a" class="x_Hyperlink x_SCXW33638199 x_BCX8 x_OWAAutoLink" title="mailto:iai-cdt@bristol.ac.uk" href="mailto:iai-cdt@bristol.ac.uk" data-linkindex="0">iai-cdt@bristol.ac.uk</a>&nbsp;</p></p><br><br><b><p><span style="color: rgb(0, 112, 192);"><strong><span class="TextRun SCXW150979733 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW150979733 BCX8" data-ccp-parastyle="List Bullet">Message from the Director</span></span><span class="EOP Selected SCXW150979733 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:360,&quot;335559740&quot;:240,&quot;335559991&quot;:360}">&nbsp;</span></strong></span></p></b><br><div class="x_elementToProof" data-olk-copy-source="MessageBody">From the 20 April, we will be welcoming Helen as a temporary member of staff to help with the admin for the PrO-AI for a couple of months whilst we recruit a replacement for Wanli. Helen&rsquo;s working hours will be 1-5pm, Monday-Friday. The PrO-AI mailbox will not be monitored outside these times so please allow sufficient time for queries/requests to be responded to.</div>
<p class="x_elementToProof">There will be no newsletter either side of the Spring university closure days (<em>3 April - 7 April</em>); the next newsletter will appear on Friday 17 April (<em>tentative</em>).</p><br><br><b><p><span style="color: rgb(191, 143, 0);"><strong><span class="TextRun SCXW157421059 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW157421059 BCX8">Internal call for Google PhD Fellowship applications now open</span></span></strong></span></p></b><br><div class="OutlineElement Ltr SCXW149544383 BCX8">
<p class="Paragraph SCXW149544383 BCX8"><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8">The 2026 call for&nbsp;</span></span><a class="Hyperlink SCXW149544383 BCX8" href="https://research.google/outreach/phd-fellowship/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW149544383 BCX8">Google PhD Fellowships</span></span></a><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8">&nbsp;is now open! Bristol can nominate up to three students for this prestigious award, and we invite short applications for internal review&nbsp;</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW149544383 BCX8">by Friday 27th March 2026, 17:00</span></span><span class="TextRun Underlined SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8">,&nbsp;</span></span><a class="Hyperlink SCXW149544383 BCX8" href="https://forms.office.com/e/tfLrn7wQGN" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW149544383 BCX8">through this Microsoft form</span></span></a><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8">. The three strongest eligible candidates will then be invited to complete a full proposal in time for the final Google deadline on 30th&nbsp;</span><span class="NormalTextRun SpellingErrorV2Themed SCXW149544383 BCX8">April.</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SpellingErrorV2Themed SCXW149544383 BCX8">How</span><span class="NormalTextRun SCXW149544383 BCX8">&nbsp;to&nbsp;</span><span class="NormalTextRun SCXW149544383 BCX8">submit</span><span class="NormalTextRun SCXW149544383 BCX8">&nbsp;an internal application</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8">&nbsp;Please complete this short form:&nbsp;</span></span><a class="Hyperlink SCXW149544383 BCX8" href="https://forms.office.com/e/tfLrn7wQGN" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW149544383 BCX8">Google PhD Fellowships 2026 - Internal Call</span></span></a><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8">&nbsp;Where possible, proposals should be&nbsp;</span><span class="NormalTextRun SCXW149544383 BCX8">submitted</span><span class="NormalTextRun SCXW149544383 BCX8">&nbsp;by candidates&rsquo; supervisors. Proposals&nbsp;</span><span class="NormalTextRun SCXW149544383 BCX8">submitted</span><span class="NormalTextRun SCXW149544383 BCX8">&nbsp;directly by students currently enrolled at Bristol will, however, also be accepted. Responses should include:&nbsp;</span></span><span class="EOP SCXW149544383 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW149544383 BCX8">
<ol class="NumberListStyle1 SCXW149544383 BCX8" role="list" start="1">
<li class="OutlineElement Ltr SCXW149544383 BCX8" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="" data-listid="5" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:360,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;singleLevel&quot;}" data-aria-posinset="1" data-aria-level="1">
<p class="Paragraph SCXW149544383 BCX8"><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">Student details</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">,&nbsp;</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">including a short narrative description of research experience and&nbsp;</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">track record</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">, as well as details of supervisor,&nbsp;</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">faculty</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;and school;</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;</span></span><span class="EOP Selected SCXW149544383 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559740&quot;:240}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW149544383 BCX8">
<ol class="NumberListStyle1 SCXW149544383 BCX8" role="list" start="2">
<li class="OutlineElement Ltr SCXW149544383 BCX8" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="" data-listid="5" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:360,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;singleLevel&quot;}" data-aria-posinset="2" data-aria-level="1">
<p class="Paragraph SCXW149544383 BCX8"><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">Project summary (maximum 500 words)</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;to be uploaded.&nbsp;</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">The project summary should be accessible for those who are not specialists in&nbsp;</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW149544383 BCX8" data-ccp-parastyle="List Number">specific</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;field of&nbsp;</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW149544383 BCX8" data-ccp-parastyle="List Number">candidate&rsquo;s</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;research. If a candidate is successful in receiving a nomination, they will be invited to make the proposal in greater technical detail at the formal application stage;</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;</span></span><span class="EOP Selected SCXW149544383 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559740&quot;:240}">&nbsp;</span></p>
</li>
</ol>
</div>
<div class="ListContainerWrapper SCXW149544383 BCX8">
<ol class="NumberListStyle1 SCXW149544383 BCX8" role="list" start="3">
<li class="OutlineElement Ltr SCXW149544383 BCX8" role="listitem" aria-setsize="-1" data-leveltext="%1." data-font="" data-listid="5" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:360,&quot;335559991&quot;:360,&quot;469769242&quot;:[65533,0],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;%1.&quot;,&quot;469777815&quot;:&quot;singleLevel&quot;}" data-aria-posinset="3" data-aria-level="1">
<p class="Paragraph SCXW149544383 BCX8"><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">Candidate&nbsp;</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW149544383 BCX8" data-ccp-parastyle="List Number">CV</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;</span></span><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">to be uploaded. Please&nbsp;</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">don&rsquo;t</span><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;hesitate to get in touch at&nbsp;</span></span><a class="Hyperlink SCXW149544383 BCX8" href="mailto:doctoral-college@bristol.ac.uk" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">doctoral-college@bristol.ac.uk</span></span></a><span class="TextRun SCXW149544383 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW149544383 BCX8" data-ccp-parastyle="List Number">&nbsp;if you have any further questions about this opportunity.&nbsp;</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW149544383 BCX8"><span class="SCXW149544383 BCX8">&nbsp;</span><br class="SCXW149544383 BCX8"></span><span class="EOP Selected SCXW149544383 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559740&quot;:240}">&nbsp;</span></p>
</li>
</ol>
</div><br><br><b><p><span style="color: rgb(168, 93, 156);"><strong><span class="TextRun SCXW157830351 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW157830351 BCX8">Bristol Doctoral College (BDC) Events and Opportunities&nbsp;</span></span><span class="EOP Selected SCXW157830351 BCX8" data-ccp-props="{}">&nbsp;</span></strong></span></p></b><br><div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><strong><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">1. 5 Weeks of Wellbeing (upcoming events for PGR students)&nbsp;&nbsp;</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></strong></p>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">This March,&nbsp;</span><span class="NormalTextRun SCXW182579761 BCX8">we&rsquo;re</span><span class="NormalTextRun SCXW182579761 BCX8">&nbsp;inviting PGR students to slow down, breathe out, and make space for the parts of life that&nbsp;</span><span class="NormalTextRun SCXW182579761 BCX8">don&rsquo;t</span><span class="NormalTextRun SCXW182579761 BCX8">&nbsp;revolve around research. Over five themed weeks,&nbsp;</span></span><a class="Hyperlink SCXW182579761 BCX8" href="https://www.bristol.ac.uk/doctoral-college/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW182579761 BCX8">Bristol Doctoral College</span></span></a><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">&nbsp;will be sharing activities designed to boost your wellbeing, spark joy, help you connect with the PGR community, and reconnect with yourself</span><span class="NormalTextRun SCXW182579761 BCX8">.&nbsp;&nbsp;</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div>
<div class="ListContainerWrapper SCXW182579761 BCX8">
<ul class="BulletListStyle1 SCXW182579761 BCX8" role="list">
<li class="OutlineElement Ltr SCXW182579761 BCX8" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="1" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:360,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;singleLevel&quot;}" data-aria-posinset="9" data-aria-level="1">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8" data-ccp-parastyle="List Bullet">Week 4 (23 - 27 March) Learn a New Skill&nbsp;&nbsp;</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559740&quot;:240}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="ListContainerWrapper SCXW182579761 BCX8">
<ul class="BulletListStyle1 SCXW182579761 BCX8" role="list">
<li class="OutlineElement Ltr SCXW182579761 BCX8" role="listitem" aria-setsize="-1" data-leveltext="" data-font="Symbol" data-listid="1" data-list-defn-props="{&quot;335552541&quot;:1,&quot;335559685&quot;:360,&quot;335559991&quot;:360,&quot;469769226&quot;:&quot;Symbol&quot;,&quot;469769242&quot;:[8226],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;&quot;,&quot;469777815&quot;:&quot;singleLevel&quot;}" data-aria-posinset="10" data-aria-level="1">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8" data-ccp-parastyle="List Bullet">Week 5 (30 March - 3 April) Be Mindful&nbsp;&nbsp;</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559740&quot;:240}">&nbsp;</span></p>
</li>
</ul>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">Get to know the PGR Clubs, join the lunchtime Wednesday Wellbeing Walks, or sign up for one of our other workshops,&nbsp;</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW182579761 BCX8">think</span><span class="NormalTextRun SCXW182579761 BCX8">&nbsp;zine making, yoga, a mending workshop, a group cycle ride, or even a soothing sound bath. All the events are free to attend and exclusively for postgraduate researchers</span><span class="NormalTextRun SCXW182579761 BCX8">.&nbsp;&nbsp;</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">See all the upcoming opportunities on BDC&nbsp;</span></span><a class="Hyperlink SCXW182579761 BCX8" href="https://www.bristol.ac.uk/doctoral-college/events/" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW182579761 BCX8">events calendar</span></span></a><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">, just filter the tags to 5 Weeks of Wellbeing.&nbsp;</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><strong><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">2. ND x LGBTQ+ Network Activity-Based Mixer</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></strong></p>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">Date:&nbsp;</span></span><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">31 March, 16:30 - 17:00</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">Location:&nbsp;</span></span><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">PGR Hub</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">Event welcome to any PGR or staff identifying as Neurodivergent or LGBTQ+.</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">The Neurodivergent PGR Network, LGBTQ+ Staff Network, and Trans &amp; Non-binary PGR Networks will be joining for an evening of crafts and mingling. Lego, paper crafts, and&nbsp;</span><span class="NormalTextRun SpellingErrorV2Themed SCXW182579761 BCX8">colouring</span><span class="NormalTextRun SCXW182579761 BCX8">&nbsp;sheets will be provided - feel free to bring your own project along, come just to chat, or just to hang out in a friendly, inclusive, and low-pressure environment.</span></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div>
<div class="OutlineElement Ltr SCXW182579761 BCX8">
<p class="Paragraph SCXW182579761 BCX8"><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">Please email&nbsp;</span></span><a class="Hyperlink SCXW182579761 BCX8" href="mailto:nd-pgr-network@bristol.ac.uk?subject=&amp;body=" target="_blank" rel="noreferrer noopener"><span class="TextRun Underlined SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW182579761 BCX8">nd-pgr-network@bristol.ac.uk</span></span></a><span class="TextRun SCXW182579761 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="auto"><span class="NormalTextRun SCXW182579761 BCX8">&nbsp;if you have any questions or would like to register your interest.</span></span><span class="LineBreakBlob BlobObject DragDrop SCXW182579761 BCX8"><span class="SCXW182579761 BCX8">&nbsp;</span><br class="SCXW182579761 BCX8"></span><span class="EOP Selected SCXW182579761 BCX8" data-ccp-props="{}">&nbsp;</span></p>
</div><br><br><b><p class="x_elementToProof"><span style="color: rgb(70, 156, 146);"><strong><span class="markbxtidyohu" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="" data-olk-copy-source="MessageBody">Global</span>&nbsp;<span class="markkjy8wz63w" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="">Lounge</span>&nbsp;- Spring vacation events (19 March to 10 April)</strong></span></p></b><br><div class="x_elementToProof">
<p class="x_elementToProof"><span data-olk-copy-source="MessageBody">If you are staying in Bristol over the vacation period,&nbsp;it&rsquo;s&nbsp;a great chance to meet up with others, learn about spring and Easter&nbsp;traditions&nbsp;and enjoy some free chocolate mini eggs! Come along each week to Culture Club, Language&nbsp;Caf&eacute;&nbsp;and Friday Hangouts. Make friends from around the world, learn something&nbsp;new&nbsp;and enjoy our friendly, welcoming community. There will be an event on the last day before closure, Thursday 2 April, and then after the University reopens on Wednesday 8 April.&nbsp;</span></p>
</div>
<div class="x_elementToProof">
<p class="x_elementToProof">See&nbsp;all of&nbsp;upcoming events on&nbsp;<u><a id="OWAde23820a-6e2e-e291-924b-3f81f5aef429" class="x_Hyperlink x_SCXW33638199 x_BCX8 x_OWAAutoLink" title="https://global-lounge.bristol.ac.uk/events/" href="https://global-lounge.bristol.ac.uk/events/" target="_blank" rel="noreferrer noopener" data-auth="NotApplicable" data-linkindex="13"><span class="markbxtidyohu" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="">Global</span>&nbsp;<span class="markkjy8wz63w" data-markjs="true" data-ogac="" data-ogab="" data-ogsc="" data-ogsb="">Lounge</span>: Upcoming events</a></u>&nbsp;</p>
</div><br><br><b><p><span style="color: rgb(230, 126, 35);"><strong>University of Bristol</strong><strong> Innovation </strong><strong>Showcase 2026</strong></span></p></b><br><p><strong>Time</strong>: 14:00 - 18:30</p>
<p><strong>Location</strong>: Watershed</p>
<p>The Centre for Innovation and Entrepreneurship has been creating change-makers for 10 years!</p>
<p>The 2026 Showcase and Runway Awards is your chance to celebrate and look forward to the future as we make the move to our new Temple Quarter Campus.&nbsp;Meet the brilliant minds of our 2026 graduating class and connect with entrepreneurs, businesses and innovators who are shaping the future. Hear about our graduating students&rsquo; projects at the Showcase, tackling everything from fresh water scarcity to electric vehicle adoption and elite athlete recovery; ideas that will define the next decade.</p>
<p>Take your seat for the Runway Awards and see the Centre&rsquo;s entrepreneurs pitch live for a share of &pound;75,000 in funding. With 2026 a milestone year for the Centre, this is the perfect moment to be part of the next chapter in Bristol&rsquo;s innovation success story.</p>
<p><a href="https://www.eventbrite.co.uk/e/university-of-bristol-innovation-showcase-2026-tickets-1981136714243?aff=UniversityExternalEventPage26">Reserve your spot here.&nbsp;</a></p><br><br><b><p><span style="color: rgb(191, 143, 0);"><strong>Around Bristol</strong></span></p></b><br><p><strong>AJ Bell Great Bristol 10K 2026</strong></p>
<p>Over 950 of our community participate in the annual Great Bristol run. Come and join us and conquer the streets ... run, walk or jog the&nbsp;<strong>Great Bristol 10K</strong> with us.&nbsp;</p>
<p>Event details:</p>
<ul>
<li>Provisional 10K start time: 8 am</li>
<li>Race packs: when entry confirmed with the Great Run Company they will be posted to your chosen address</li>
<li>Places are available on a first come first serve basis. Subsidised University of Bristol entries will close: Sunday 12 April 2026 (or before if the event reaches capacity).</li>
</ul>
<p>Find out more at the <a href="https://www.bristol.ac.uk/events/#event=aj-bell-great-bristol-10k-2026;instance=20260510080000?popup=1&amp;lang=en-UK">Event page here.</a></p><br><br><b><p><span style="color: rgb(227, 122, 203);"><strong>British Summer Time</strong></span></p></b><br><p>⏰ This is a reminder that the clocks will go forward 1 hour at 1am on 29 March - the official start of British Summer Time. Please prepare emotionally for the loss of precious sleep.</p><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b><p><span style="color: rgb(196, 89, 17);"><strong><span class="TextRun SCXW60476628 BCX8" lang="EN-US" xml:lang="EN-US" data-contrast="none"><span class="NormalTextRun SCXW60476628 BCX8">CDT&nbsp;</span><span class="NormalTextRun SCXW60476628 BCX8">AI Symposium &ndash; Foundation and Applications of Trustworthy AI</span></span><span class="EOP SCXW60476628 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:0,&quot;335559740&quot;:257,&quot;469777462&quot;:[1134],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></strong></span></p> - 2026-03-27</b><br><b><p><span style="color: rgb(230, 126, 35);"><strong>University of Bristol</strong><strong> Innovation </strong><strong>Showcase 2026</strong></span></p> - 2026-04-15</b><br><b><p><span style="color: rgb(191, 143, 0);"><strong>Around Bristol</strong></span></p> - 2026-05-10</b><br>