project:
  type: website

website:
  title: "Practice-Oriented AI CDT"
  sidebar:
    collapse-level: 1
    style: "docked"
    contents:
      - section: "Home"
        contents:
          - index.qmd
          - about.qmd
          - people.qmd
          - partners.qmd
          - events.qmd
          - blog.qmd
          - equality_diversity_and_inclusion.qmd
          - contact.qmd
        text: "Equality Diversity and Inclusion"
      - section: "Programme details"
        contents:
          - foundation_year.qmd
          - summer_projects.qmd
          - phd_projects.qmd
      - section: "Apply"  
        contents:
          - why_study_with_us.qmd
          - how_to_apply.qmd
          - funding.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



