project:
  type: website

website:
  title: "Practice-Oriented AI CDT"
  
  sidebar:
    id: "main-sidebar"
    collapse-level: 2
    style: "docked"
    logo: "pro-ai-logo.gif"
    background: "#f8fafc" 
    contents:
      - section: "Home"
        contents:
          - text: "Overview"
            file: index.qmd
          - text: "About the CDT"
            file: about.qmd
          - text: "Partners"
            file: partners.qmd
          - text: "Equality, Diversity & Inclusion"
            file: equality_diversity_and_inclusion.qmd
          - text: "Contact Us"
            file: contact.qmd

      - section: "Programme Details"
        contents:
          - text: "Foundation Year"
            file: foundation_year.qmd
          - text: "Summer Projects"
            file: summer_projects.qmd
          - text: "PhD Projects"
            file: phd_projects.qmd

      - section: "Our People"
        contents:
          - text: "Cohort 2024"
            file: people/cohort_2024.qmd
          - text: "Cohort 2025"
            file: people/cohort_2025.qmd
          - text: "Supervisors"
            file: people/supervisors.qmd
          - text: "Professional Staff"
            file: people/staff.qmd

      - section: "Apply"  
        contents:
          - text: "Why Study With Us"
            file: why_study_with_us.qmd
          - text: "How to Apply"
            file: how_to_apply.qmd
          - text: "Funding"
            file: funding.qmd

      - section: "News & Community"
        contents: 
          - text: "Events"
            file: events.qmd
          - text: "Blog"
            file: blog.qmd
          - text: "Latest Newsletter"
            file: newsletter.qmd
          - text: "Previous Issues"
            file: previous_issues.qmd

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    css: styles.css
    toc: true
    linkcolor: "#b01c2e"