project:
  type: website

website:
  title: "Practice-Oriented AI CDT"
  sidebar:
    collapse-level: 2
    style: "docked"
    logo: "pro-ai-logo.gif"
    contents:
      - section: "Home"
        contents:
          - index.qmd
          - about.qmd
          - partners.qmd
          - events.qmd
          - blog.qmd
          - equality_diversity_and_inclusion.qmd
          - contact.qmd
        text: "Equality Diversity and Inclusion"
      - section: "Programme details"
        contents:
          - foundation_year.qmd
          - summer_projects.qmd
          - phd_projects.qmd
      - section: "People"
        contents:
          -  people/cohort_2024.qmd
          -  people/cohort_2025.qmd
          -  people/staff.qmd
          -  people/supervisors.qmd
      - section: "Apply"  
        contents:
          - why_study_with_us.qmd
          - how_to_apply.qmd
          - funding.qmd
      - section: "Newsletter"
        contents: 
          - newsletter.qmd
          - previous_issues.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



