---
title: "About the PrO-AI CDT"
---

The UKRI AI Centre for Doctoral Training in Practice-Oriented Artificial Intelligence (PrO-AI) will deliver the next generation of innovators producing state-of-the-art AI solutions in existing and future domains that will transform UK science, economy and society. Founded on our extensive experience in doctoral training for designing and building complex human-centred AI pipelines, and developed in collaboration with a broad range of industry partners, the PrO-AI CDT will equip researchers with essential skills in co-designing and building practice-oriented AI applications across science and research domains of national importance. The specific objectives are:

1. to recruit highly motivated postgraduate students from computer science, mathematics, and cognate disciplines following best practices in equality, diversity and inclusion, and create an immersive training experience which introduces and reinforces the principles needed to successfully design effective and trustworthy AI solutions across sicence and research domains, delivered within a distinctive cohort training environment;

2. to train and deliver PhD graduates able to critically recognise the potential for AI solutions in a particular domain, work with domain experts to elicit requirements and articulate what AI capabilities are needed, translate the requirements into system specifications taking into account legal and ethical considerations, implement a prototype AI system, and deploy the AI system in production and continuously assess its performance in solving the originally stated problem;

3. to promote a human-in-the-loop ethos that emphasises technology co-design for and with humans, with PhD students mastering the techniques for eliciting requirements from domain experts, overcoming existing barriers for the adoption of AI in key fields such as health, environment and energy, and creative industries -- and develop world-class research in these areas;

4. to set the highest standards for our PhD students of responsible innovation with particular emphasis on AI-specific issues when co-designing AI solutions with domain experts, such as transparency, explainability, accountability, fairness, trustworthiness and privacy, and establishing clear guidelines for the sustainable use of data, software and compute, leading to net zero;

5. to train "AI ambassadors" who, through their deep understanding of the strengths and limitations of artificial intelligence in different areas, can contribute to and lead the public debate on AI and its relationship to society;

6. to support the development of entrepreneurial skills and intellectual property, as our graduates will be able to seamlessly work across domains, establishing and contributing to AI teams in different fields;

7. to be an exemplar for technology-supported cohort-based training, using the latest developments and insights in flipped-classroom teaching and teamwork, open software development tools and platforms with input from our industry partners, and cross-cohort mentoring;

8. to build long-term relationships between the CDT and its industrial partners, government and regulators, enhancing the cohort provision through placements, co-supervised projects and research collaborations;

9. to contribute to the "democratisation of AI" and reduce inequality within the sector by promoting take-up of relevant AI techniques in SMEs across sectors;

10. to consolidate and expand existing expertise at Bristol as a leading international research training centre with relationships with global partners, building a community that will have access to expertise, and can engage and interact with the CDT through a programme of regular events, including workshops, summer schools and networking activities.