---
title: ""
---

<div class="mx-auto mt-4" style="max-width: 850px;">

<h1 class="title fw-bold" style="color: #b01c2e; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 2rem;">
  Equality, Diversity & Inclusion
</h1>

<div style="text-align: justify;" class="lh-base">

The Equality, Diversity and Inclusion (EDI) strategy of the PrO-AI CDT aims to ensure an equitable, diverse and inclusive environment for all involved with the CDT, including students, recruitment candidates, academics, centre management, industry partners, and research participants.

We intend the CDT to be an active driver of EDI practices, proactively going beyond University policy and statutory compliance. This is not just because it is a moral and ethical approach: our central goal is to train a generation of PhD graduates able to understand heterogeneous practices and settings in order to design AI solutions that are sensitive to that heterogeneity. 

Bringing together people with diverse backgrounds and ideas is crucial for achieving this goal. In recognising our differences, we aim to provide an equitable platform for all, with a number of actions to support a diverse and inclusive CDT community.

</div>

</div>