---
title: "Practice Oriented AI CDT"
---

> Our mission is to train the next generations of AI innovators, equipping them with the expertise and skills to co-design and build practice-oriented AI systems for science and research domains of key national importance. Our innovative, cohort-based training programme will deliver highly-trained PhD graduates with the transferable skills to deliver impact while solving societally important problems in responsible ways.

Practice-oriented AI is about bridging the gap between between complex problem domains such as those found in science and research, and AI algorithms and techniques that could be used to solve problems in those domains. PrO-AI research will fundamentally advance the state of the art in methodologies for building AI systems, similar to the way software engineering developed sophisticated methodologies for programmers to work in a problem-driven way. This will result in AI systems that are demonstrably finely attuned to the problem they solve, and hence more usable, quicker to develop, and easier to maintain. As such, beneficiaries include everyone working with AI systems, be they users, developers, managers, decision makers, etc. 

While the current, media-driven narrative focuses on the disruptive nature of selected AI technologies, research organisations working towards incorporating AI methods strongly prefer to do so in a way that maximally respects their well-established practices. The key AI challenges of tomorrow are posed by the need for a deeper cooperation and alignment between AI systems, AI practitioners, and domain experts, the latter being the source of both relevant case-specific knowledge and requirements with regards to functionality, robustness, transparency, accountability and fairness for a given application. In other words, we need AI experts with the ability to act as a bridge between domain experts and AI technology. But rather than delivering 'AI for x' experts for a fixed domain x -- which might quickly lose its importance or utility -- the PrO-AI doctoral training programme will deliver experts with the flexibility to adapt to new domains during the course of their career.

The PrO-AI CDT pulls together the University of Bristol's proven track record in doctoral AI training and its unique and comprehensive strengths in AI applied to a range of science and research areas including health, environment and energy, and creative industries, to deliver highly-trained AI innovators with the transferable skills to deliver societal impact across domains.
