---
execute:
  echo: false
format:
  html:
    df-print: paged
    toc: true
title: Newsletter Issue - 01-05-2025

---
<h2>CDT Weekly Newsletter</h2><br><ul><li>Student reps for next academic year</li><li>Jean Golding Institute    Sustainable Innovation Lunch – Bristol</li></ul><p><p>Welcome to this week's issue of the newsletter.</p></p><br><br><b>Student reps for next academic year</b><br><p class="x_MsoNormal" style="margin-bottom: 9.6pt; line-height: 106%;"><span data-olk-copy-source="MessageBody">It&rsquo;s time to organise student reps for the next academic year, with two reps being needed for each cohort. Roles still to be filled for CDT23 and CDT22. Please email </span><span lang="EN-US" style="font-size: 11.0pt; line-height: 106%; font-family: 'Calibri',sans-serif;"><a title="mailto:iai-cdt@bristol.ac.uk" href="mailto:iai-cdt@bristol.ac.uk" data-linkindex="1"><span lang="EN-GB" style="font-size: 12pt; line-height: 106%; font-family: 'Aptos', sans-serif; color: rgb(5, 99, 193) !important;">iai-cdt@bristol.ac.uk</span></a></span> by <strong>17 April</strong> if you are willing to take on the role.</p><br><br><b>Jean Golding Institute    Sustainable Innovation Lunch – Bristol</b><br><p class="x_MsoNormal" style="margin-bottom: 9.6pt; line-height: 106%;"><span data-olk-copy-source="MessageBody">Join us for this event to explore the resources to support researchers in developing breakthrough innovations and navigating their entrepreneurial journey. Focussing on opportunities in eco and sustainability innovation, we welcome academics from all disciplines interested in turning research into impact. Learn about funding, educational programs, and resources designed to accelerate innovation in your field. </span><span lang="EN-US" style="font-size: 11.0pt; line-height: 106%; font-family: 'Calibri',sans-serif;"><a title="https://nucleate.org/" href="https://nucleate.org/" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" data-linkindex="3"><span lang="EN-GB" style="font-size: 12pt; line-height: 106%; font-family: 'Aptos', sans-serif; color: rgb(5, 99, 193) !important;">Nucleate</span></a></span> Translate is an initiative designed to identify and bring together top-tier scientific and business talent who can contribute to research and science entrepreneurship within ARIA&rsquo;s Opportunity Spaces. Nucleate Identify is powered through our partnership with the Advanced Research + Invention Agency (<span lang="EN-US" style="font-size: 11.0pt; line-height: 106%; font-family: 'Calibri',sans-serif;"><a title="https://www.aria.org.uk/" href="https://www.aria.org.uk/" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable" data-linkindex="4"><span lang="EN-GB" style="font-size: 12pt; line-height: 106%; font-family: 'Aptos', sans-serif; color: rgb(5, 99, 193) !important;">ARIA</span></a></span>).</p><br><br><h2>Forthcoming Calendar of Events</h2><br><br><b>Lunch and Learn Seminar - 2025-05-08</b><br><b>Workshop: How to Navigate the Middle Years of your Research Degree, online or in-person (hybrid session) - 2025-05-28</b><br>