---
title: "Open Research Projects"
---

(TO BE UPDATED)

Here is a list of research projects in Interactive AI that we are currently recruiting to. We are asking applicants to base their research statement on one of these. Further projects may become available in due course and will be added here.  

### Digital waste in Interactive AI 

Digital waste is defined as the use of digital infrastructure for services that are not or only partly enjoyed by the user. Design techniques that can reduce demand on infrastructure will thus contribute to the reduction of environmental impact. As Interactive AI applications embed the human in an interaction loop with a digital device, it is particularly relevant to consider digital waste. Working with Dr Daniel Schien, you will investigate digital waste from two complementary angles: reducing digital waste in Interactive AI applications; and applying Interactive AI to reduce digital waste in ICT services in general.  

### Interactive AI for dealing with bias in language 

Natural language processing (NLP) is finding new uses in a wide range of applications, such as recruitment, healthcare, policing, advertising and social media monitoring. NLP models can learn and may even amplify social biases and stereotypes, resulting in automated systems making unfair decisions against certain groups of people. To address the problem, new analysis tools are required that let domain experts probe models for different forms of bias and evaluate and adjust techniques like adversarial debiasing. Working with Dr Edwin Simpson, you will develop novel techniques and create interactive tools for analysing and correcting such biases.   

### Interactive AI to help understand Parkinson’s disease 

The availability of real-time information through the increasing capabilities of sensing devices has led to the emergence of research into Activity Recognition. Investigating the activities and sleep patterns of patients with a condition such as Parkinson’s Disease can help to understand the progression of the disease and the effect of medications. Working with Dr Zahraa Abdallah, you will develop novel Interactive AI techniques for analysing accelerometer data collected by wrist-worn sensors, examine episodes of sleep and identify distinguishing features, unusual patterns, and sleep quality measures.   

### Prosociality as a foundation for ethics and fairness in Interactive AI 

Current research on ethics and fairness in Interactive AI focuses on a single agent, often associated with an entity such as a mortgage lender or a judge. It is often more appropriate to model ethics and fairness as a social concern between prosocial agents. Working with Dr Nirav Ajmeri, you will uncover the principles of prosociality on which AI agents can interact with each other and with humans to realize fair outcomes for the humans involved. Such agents would (autonomously) behave prosocially and (collaboratively) strengthen prosociality among human actors by facilitating their awareness of each other's needs and preferences.  

### Interactive modelling of language 

Within the field of computational linguistics there are different ways to model language: corpus based approaches which generate meaning from large bodies of text; the evolutionary linguistic approach which derives meaning from interaction with the outside world and with other agents; and the vector-symbolic approach which can be implemented in more biologically plausible artificial neural networks. Working with Dr Martha Lewis, you will unify these three approaches to propose a model of language that is compositional, interactive, and has a neural implementation, opening up the framework to teaching through interaction with a human. 
