---
title: ""
---

<div class="mx-auto mt-4" style="max-width: 850px;">

<h1 class="title fw-bold" style="color: #b01c2e; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 2rem;">
  Why Study With Us
</h1>

<div style="text-align: justify;" class="lh-base">

Bristol is a fantastic place to live with a lively AI, machine learning and data science community. In addition to being part of a world-leading research and training environment, Interactive AI students will benefit from a wide range of extra training opportunities, events and support structures: 

1. Students have access to a wide range of research seminars, reading groups and other events on relevant topics at Bristol, including an IAI Spring Research Conference, IAI Summer School and an Interactive AI seminar series. 
2. A programming trainer will be available to provide advanced training and support to students in using the university’s high-performance computing and data storage systems. 
3. Bristol is a full partner of the Alan Turing Institute, the national research institute for Data Science and AI, which will provide access to further training and CDT-related activities.
4. The students will have the option to complete an internship or research visit to a national/international academic partner or industrial lab for one to three months. Leading universities (e.g. KU Leuven, UCL, Leiden, Nottingham, UP Valencia, Gent, Aalto, LMU Munich) and companies (e.g. Amazon, Microsoft, Thales) have agreed to host CDT students.
5. Professional and personal development opportunities include courses on entrepreneurial skills and public engagement training.   
6. Access to other training elements from the wider AI and domain-specific courses that the University offers.


</div>

</div>

